#!/usr/bin/env python3
"""
Crema brand mark — single source of truth generator.

The mark is a copper disc + a serif "C" (Newsreader). To stay font-INDEPENDENT
(so it renders identically in every shell + as favicon.ico/png/svg without the
fragile <foreignObject>+webfont trick), we bake the actual Newsreader glyph
outline into a plain SVG <path> with fontTools, then rasterise to png/ico.

Two optical variants (this is real CSS `font-optical-sizing`, not a hack):
  • canonical (opsz=34, wght=500) — refined display C. Used for the in-app mark,
    the scalable favicon.svg, and the large PWA icons (192/512). Matches the
    PWA favicon's 34px optical size.
  • small     (opsz=6,  wght=600) — bolder, simpler, slightly larger + centred.
    Used for the tiny raster favicons (16/32/48 + favicon.ico) where the refined
    C's thin terminals would mud out.

Layout: positioned by the exact CSS the shells use — font-size 0.529·disc,
flex-centred, line-height:1, letter-spacing -0.04em — using the font's own
advance + hhea metrics, so the baked C sits where the live font would render it.

Colours: disc #C7763B (copper-500), ink #1F1812 (fg-on-accent).

Usage:  python3 generate_mark.py            # writes crema-mark*.svg here
        python3 generate_mark.py --assets   # + rsvg/magick → png/ico (needs both)

Requires: fonttools (pip install fonttools). Downloads Newsreader VF on first run.
"""
import os, subprocess, sys, urllib.request

HERE = os.path.dirname(os.path.abspath(__file__))
FONT = os.path.join(HERE, "Newsreader.ttf")
FONT_URL = "https://github.com/google/fonts/raw/main/ofl/newsreader/Newsreader%5Bopsz,wght%5D.ttf"
DISC = 64.0
COPPER, INK = "#C7763B", "#1F1812"

def ensure_font():
    if not os.path.exists(FONT):
        print("downloading Newsreader VF…")
        urllib.request.urlretrieve(FONT_URL, FONT)

def bake(wght, opsz, *, target_h=None, cx=None, cy=None):
    """Return the C glyph as an SVG path 'd', positioned in the 64-unit disc.
    target_h/cx/cy override the CSS-layout placement (used for the small variant)."""
    from fontTools.ttLib import TTFont
    from fontTools.varLib.instancer import instantiateVariableFont
    from fontTools.pens.svgPathPen import SVGPathPen
    from fontTools.pens.transformPen import TransformPen
    from fontTools.pens.boundsPen import BoundsPen
    f = TTFont(FONT); instantiateVariableFont(f, {"wght": wght, "opsz": opsz}, inplace=True)
    upm = f["head"].unitsPerEm; hA, hD = f["hhea"].ascent, f["hhea"].descent
    adv = f["hmtx"]["C"][0]
    gs = f.getGlyphSet(); g = gs["C"]; bp = BoundsPen(gs); g.draw(bp)
    xMin, yMin, xMax, yMax = bp.bounds
    if target_h is not None:                         # explicit placement (small variant)
        s = target_h / (yMax - yMin)
        tx = cx - s * (xMin + xMax) / 2.0
        ty = cy + s * (yMin + yMax) / 2.0
    else:                                            # faithful CSS layout (canonical)
        F = 0.529 * DISC; s = F / upm; LS = -0.04 * F
        tx = (DISC - (adv * s + LS)) / 2.0
        ty = DISC / 2.0 + s * (hA + hD) / 2.0        # baseline; C rides above → up-shift
    pen = SVGPathPen(gs); g.draw(TransformPen(pen, (s, 0, 0, -s, tx, ty)))
    return pen.getCommands()

def svg(d):
    """Disc mark — copper circle + C, transparent corners. Favicon + standard use."""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">'
            f'<circle cx="32" cy="32" r="32" fill="{COPPER}"/>'
            f'<path fill="{INK}" d="{d}"/></svg>\n')

def svg_full(d):
    """Full-bleed mark — copper square (no transparency) + C. For PWA *maskable*
    icons + iOS apple-touch (the OS masks to circle/squircle/rounded-rect, so the
    bg must fill the square and the glyph must sit inside the ~80% safe zone)."""
    return (f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64">'
            f'<rect width="64" height="64" fill="{COPPER}"/>'
            f'<path fill="{INK}" d="{d}"/></svg>\n')

CORE_BRAND_RS = os.path.normpath(os.path.join(HERE, "..", "core", "de1-domain", "src", "brand.rs"))

_RUST_TEMPLATE = r'''//! Crema brand mark — GENERATED by `brand/generate_mark.py`; do not edit by hand.
//!
//! The single source of truth for the Crema "C": the Newsreader-500 glyph baked
//! to a font-free SVG path (renders identically everywhere — no font, no
//! `<foreignObject>`). The web (`static/favicon.svg`, PWA icons) and Android
//! (`ic_crema_logo.xml`) generate their committed assets from this same path.
//! Kept as plain domain data (no FFI export) until a shell renders it at runtime.

/// Copper disc / app-icon background — `copper-500`.
pub const COPPER: &str = "__COPPER__";
/// Ink / glyph colour — `fg-on-accent`.
pub const INK: &str = "__INK__";
/// The disc-placement "C" path, in a `0 0 64 64` viewBox.
pub const MARK_PATH: &str = "__DISC__";
/// The full-bleed (maskable / app-icon) "C" path — centred + larger.
pub const MARK_PATH_MASKABLE: &str = "__MASK__";

/// Disc mark as a standalone SVG document (transparent corners; favicon + in-app).
pub fn mark_svg() -> String {
    format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\"><circle cx=\"32\" cy=\"32\" r=\"32\" fill=\"{}\"/><path fill=\"{}\" d=\"{}\"/></svg>",
        COPPER, INK, MARK_PATH
    )
}

/// Full-bleed maskable mark (copper square + C) — PWA maskable / iOS / app icon.
pub fn mark_maskable_svg() -> String {
    format!(
        "<svg xmlns=\"http://www.w3.org/2000/svg\" viewBox=\"0 0 64 64\" width=\"64\" height=\"64\"><rect width=\"64\" height=\"64\" fill=\"{}\"/><path fill=\"{}\" d=\"{}\"/></svg>",
        COPPER, INK, MARK_PATH_MASKABLE
    )
}

#[cfg(test)]
mod tests {
    use super::*;
    #[test]
    fn builds_valid_svg() {
        assert!(mark_svg().starts_with("<svg"));
        assert!(mark_svg().contains(MARK_PATH));
        assert!(mark_svg().contains(COPPER));
        assert!(mark_maskable_svg().contains("<rect"));
    }
}
'''

def write_core(d_disc, d_mask):
    """Emit the canonical mark into de1-domain as shared Rust source (no drift)."""
    if not os.path.isdir(os.path.dirname(CORE_BRAND_RS)):
        print(f"(skip core: {os.path.dirname(CORE_BRAND_RS)} not found)")
        return
    rs = (_RUST_TEMPLATE.replace("__COPPER__", COPPER).replace("__INK__", INK)
          .replace("__DISC__", d_disc).replace("__MASK__", d_mask))
    open(CORE_BRAND_RS, "w").write(rs)
    print(f"wrote {CORE_BRAND_RS}")


def main():
    ensure_font()
    d_disc = bake(500, 34)                                  # off-centre CSS layout (favicon/disc)
    d_mask = bake(500, 34, target_h=34.0, cx=32.0, cy=32.5)  # centred + larger (square app icon)
    open(os.path.join(HERE, "crema-mark.svg"), "w").write(svg(d_disc))
    open(os.path.join(HERE, "crema-mark-maskable.svg"), "w").write(svg_full(d_mask))
    print("wrote crema-mark.svg (disc) + crema-mark-maskable.svg (full-bleed) — opsz-34")
    write_core(d_disc, d_mask)
    if "--assets" in sys.argv:
        out = os.path.join(HERE, "out"); os.makedirs(out, exist_ok=True)
        disc = os.path.join(HERE, "crema-mark.svg")
        mask = os.path.join(HERE, "crema-mark-maskable.svg")
        def render(src, size, dst):  # rsvg rasterises the SVG at the exact size
            subprocess.run(["rsvg-convert", "-w", str(size), "-h", str(size), src, "-o", dst], check=True)
        # Favicon (disc, transparent corners) → multi-res .ico + 32px fallback
        for sz in (16, 32, 48): render(disc, sz, f"{out}/mark-{sz}.png")
        render(disc, 32,  f"{out}/favicon-32.png")
        subprocess.run(["magick", f"{out}/mark-16.png", f"{out}/mark-32.png", f"{out}/mark-48.png", f"{out}/favicon.ico"], check=True)
        # PWA install set (kept for future installable-PWA iteration):
        render(disc, 192, f"{out}/icon-192.png")            # "any" purpose
        render(disc, 512, f"{out}/icon-512.png")
        render(mask, 192, f"{out}/icon-maskable-192.png")   # "maskable" purpose (Android)
        render(mask, 512, f"{out}/icon-maskable-512.png")
        render(mask, 180, f"{out}/apple-touch-icon.png")    # iOS home screen
        render(mask, 120, f"{out}/oauth-logo-120.png")      # Google OAuth consent (square, PNG)
        print(f"rasterised → {out}/ : favicon.ico, favicon-32, icon-192/512, "
              f"icon-maskable-192/512, apple-touch-icon, oauth-logo-120 (all opsz-34)")

if __name__ == "__main__":
    main()
