//! # de1-ffi
//!
//! The UniFFI bridge: exposes [`de1_app::CremaCore`] to the Android (Kotlin)
//! shell. The bridge is deliberately thin — it wraps the core behind a mutex
//! and serializes the rich [`CoreOutput`](de1_app::CoreOutput) to JSON (the
//! "Option S" encoding from `docs/08-ffi-and-web-scope.md`). Inputs are simple
//! typed values UniFFI marshals natively.
//!
//! `unsafe` is unavoidable here — UniFFI generates the `extern "C"` FFI
//! scaffolding — which is why this crate opts out of the workspace's
//! `unsafe_code = "forbid"` lint (see `Cargo.toml`).

use std::sync::{Mutex, MutexGuard};

use de1_app::{CoreOutput, CremaCore, Source};
use de1_protocol::{MachineState, ShotSettings};

uniffi::setup_scaffolding!();

/// Which BLE characteristic an incoming notification came from — mirrors
/// [`de1_app::Source`] across the FFI boundary.
#[derive(uniffi::Enum)]
pub enum NotificationSource {
    /// The DE1 machine state / substate characteristic.
    De1State,
    /// The DE1 shot-telemetry characteristic.
    De1ShotSample,
    /// The connected scale's weight notification.
    ScaleWeight,
    /// The connected scale's command-characteristic notification (the Bookoo's
    /// `ff12` serial / settings responses).
    ScaleCommand,
    /// The DE1 water-tank level characteristic.
    De1WaterLevels,
}

impl From<NotificationSource> for Source {
    fn from(source: NotificationSource) -> Source {
        match source {
            NotificationSource::De1State => Source::De1State,
            NotificationSource::De1ShotSample => Source::De1ShotSample,
            NotificationSource::ScaleWeight => Source::ScaleWeight,
            NotificationSource::ScaleCommand => Source::ScaleCommand,
            NotificationSource::De1WaterLevels => Source::De1WaterLevels,
        }
    }
}

/// A machine state the shell can ask the DE1 to enter.
#[derive(uniffi::Enum)]
pub enum MachineRequest {
    /// Go to sleep.
    Sleep,
    /// Return to idle — also stops a running shot and wakes from sleep.
    Idle,
    /// Start an espresso shot.
    Espresso,
    /// Start steam.
    Steam,
    /// Start hot water.
    HotWater,
    /// Start a group-head flush / rinse.
    Flush,
    /// Start a descale cycle.
    Descale,
    /// Start a cleaning cycle.
    Clean,
    /// Advance to the next espresso frame.
    SkipToNext,
}

impl From<MachineRequest> for MachineState {
    fn from(request: MachineRequest) -> MachineState {
        match request {
            MachineRequest::Sleep => MachineState::Sleep,
            MachineRequest::Idle => MachineState::Idle,
            MachineRequest::Espresso => MachineState::Espresso,
            MachineRequest::Steam => MachineState::Steam,
            MachineRequest::HotWater => MachineState::HotWater,
            MachineRequest::Flush => MachineState::HotWaterRinse,
            MachineRequest::Descale => MachineState::Descale,
            MachineRequest::Clean => MachineState::Clean,
            MachineRequest::SkipToNext => MachineState::SkipToNext,
        }
    }
}

/// The DE1's steam / hot-water settings, mirrored across the FFI boundary.
///
/// [`de1_protocol::ShotSettings`] is not (and should not be) UniFFI-annotated,
/// so this bridge-local record marshals it; the bridge builds the protocol
/// type from it inside [`CremaBridge::set_steam_hotwater_settings`].
#[derive(uniffi::Record)]
pub struct SteamHotWaterSettings {
    /// Steam-control flag bits (the legacy app writes 0).
    pub steam_flags: u8,
    /// Target steam temperature, °C.
    pub steam_temp_c: f32,
    /// Steam timeout, seconds.
    pub steam_timeout_s: f32,
    /// Target hot-water temperature, °C.
    pub hot_water_temp_c: f32,
    /// Hot-water volume, mL.
    pub hot_water_volume_ml: f32,
    /// Hot-water maximum time, seconds.
    pub hot_water_timeout_s: f32,
    /// Typical espresso volume, mL.
    pub espresso_volume_ml: f32,
    /// Espresso group target temperature, °C.
    pub group_temp_c: f32,
}

impl From<SteamHotWaterSettings> for ShotSettings {
    fn from(s: SteamHotWaterSettings) -> ShotSettings {
        ShotSettings {
            steam_flags: s.steam_flags,
            steam_temp_c: s.steam_temp_c,
            steam_timeout_s: s.steam_timeout_s,
            hot_water_temp_c: s.hot_water_temp_c,
            hot_water_volume_ml: s.hot_water_volume_ml,
            hot_water_timeout_s: s.hot_water_timeout_s,
            espresso_volume_ml: s.espresso_volume_ml,
            group_temp_c: s.group_temp_c,
        }
    }
}

/// The Crema core, exposed to the Kotlin shell.
///
/// Methods that produce a [`CoreOutput`] return it as a JSON string; the shell
/// deserializes it into types generated by `typeshare`. Other methods take and
/// return plain scalars.
#[derive(uniffi::Object)]
pub struct CremaBridge {
    inner: Mutex<CremaCore>,
}

impl CremaBridge {
    /// Lock the wrapped core. The mutex is poisoned only by a panic inside a
    /// core method; the core does not panic, so this never fails in practice.
    fn core(&self) -> MutexGuard<'_, CremaCore> {
        self.inner.lock().expect("CremaCore mutex poisoned")
    }
}

impl Default for CremaBridge {
    fn default() -> CremaBridge {
        CremaBridge::new()
    }
}

#[uniffi::export]
impl CremaBridge {
    /// Create a core in the idle state.
    #[uniffi::constructor]
    pub fn new() -> CremaBridge {
        CremaBridge {
            inner: Mutex::new(CremaCore::new()),
        }
    }

    /// Feed a raw GATT notification. Returns a JSON-encoded [`CoreOutput`].
    pub fn on_notification(
        &self,
        source: NotificationSource,
        data: Vec<u8>,
        now_ms: u64,
    ) -> String {
        json(self.core().on_notification(source.into(), &data, now_ms))
    }

    /// Feed a periodic clock tick. Returns a JSON-encoded [`CoreOutput`].
    pub fn on_tick(&self, now_ms: u64) -> String {
        json(self.core().on_tick(now_ms))
    }

    /// Discard all session state — e.g. on disconnect.
    pub fn reset(&self) {
        self.core().reset();
    }

    /// Identify and connect a scale from its BLE advertised name. Returns the
    /// connected scale's display label, or `None` if the name matched no
    /// supported scale.
    pub fn connect_scale(&self, advertised_name: String) -> Option<String> {
        self.core().connect_scale(&advertised_name)
    }

    /// Arm automatic shot-stop at a weight (grams), volume (mL), and/or
    /// max-shot-time (seconds) target.
    pub fn arm_auto_stop(
        &self,
        weight_g: Option<f32>,
        volume_ml: Option<f32>,
        max_time: Option<f32>,
    ) {
        self.core().arm_auto_stop(weight_g, volume_ml, max_time);
    }

    /// Disarm automatic shot-stop.
    pub fn disarm_auto_stop(&self) {
        self.core().disarm_auto_stop();
    }

    /// Build a [`CoreOutput`] (JSON) whose command asks the DE1 to enter
    /// `state`.
    pub fn request_machine_state(&self, state: MachineRequest) -> String {
        json(self.core().request_machine_state(state.into()))
    }

    /// Build a [`CoreOutput`] (JSON) whose command tares the connected scale.
    pub fn tare_scale(&self) -> String {
        json(self.core().tare_scale())
    }

    /// What the currently-connected scale can do beyond reporting a bare
    /// weight, as a JSON-encoded `ScaleCapabilities` object — or `None` when no
    /// scale is connected.
    ///
    /// The shell deserializes the JSON into the `typeshare`-generated
    /// `ScaleCapabilities` type and drives capability-gated configuration UI
    /// off it: Crema is capability-driven, never device-driven. Returned as a
    /// JSON string, consistent with the rest of the bridge's JSON surface.
    pub fn scale_capabilities(&self) -> Option<String> {
        self.core().scale_capabilities().map(|caps| {
            serde_json::to_string(&caps)
                .expect("ScaleCapabilities is plain data and always serializes")
        })
    }

    /// Build a [`CoreOutput`] (JSON) whose command sets the connected scale's
    /// beep volume to `level`.
    ///
    /// `level` is clamped to the connected scale's `ScaleCapabilities::volume`
    /// `[min, max]` bounds. Capability-gated: the command is present only when
    /// the connected scale exposes a settable volume. Empty otherwise. Wired
    /// exactly like [`tare_scale`](Self::tare_scale).
    pub fn set_scale_volume(&self, level: u8) -> String {
        json(self.core().set_scale_volume(level))
    }

    /// Build a [`CoreOutput`] (JSON) whose command sets the connected scale's
    /// auto-standby timeout to `minutes`.
    ///
    /// `minutes` is clamped to the connected scale's
    /// `ScaleCapabilities::standby_minutes` `[min, max]` bounds. Capability-
    /// gated: the command is present only when the connected scale exposes a
    /// configurable auto-standby. Empty otherwise. Wired exactly like
    /// [`set_scale_volume`](Self::set_scale_volume).
    pub fn set_scale_standby_minutes(&self, minutes: u8) -> String {
        json(self.core().set_scale_standby_minutes(minutes))
    }

    /// Build a [`CoreOutput`] (JSON) whose command enables or disables the
    /// connected scale's flow smoothing.
    ///
    /// Capability-gated: the command is present only when the connected scale
    /// supports flow smoothing. Empty otherwise. Wired exactly like
    /// [`set_scale_volume`](Self::set_scale_volume).
    pub fn set_scale_flow_smoothing(&self, enabled: bool) -> String {
        json(self.core().set_scale_flow_smoothing(enabled))
    }

    /// Build a [`CoreOutput`] (JSON) whose command enables or disables the
    /// connected scale's anti-mistouch.
    ///
    /// Capability-gated: the command is present only when the connected scale
    /// supports anti-mistouch. Empty otherwise. Wired exactly like
    /// [`set_scale_volume`](Self::set_scale_volume).
    pub fn set_scale_anti_mistouch(&self, enabled: bool) -> String {
        json(self.core().set_scale_anti_mistouch(enabled))
    }

    /// Build a [`CoreOutput`] (JSON) whose commands switch the connected scale
    /// to display mode `mode_id`.
    ///
    /// Capability-gated: the commands are present only when the connected
    /// scale exposes switchable modes and `mode_id` is one of the listed
    /// modes. Switching a mode is **three** `WriteScale` commands, emitted in
    /// order — the shell must perform them in that order. Empty otherwise.
    /// Wired exactly like [`set_scale_volume`](Self::set_scale_volume).
    pub fn set_scale_mode(&self, mode_id: u8) -> String {
        json(self.core().set_scale_mode(mode_id))
    }

    /// Build a [`CoreOutput`] (JSON) whose command selects the connected
    /// scale's auto-stop mode (`0` = flow-stop, `1` = cup-removal).
    ///
    /// Capability-gated: the command is present only when the connected scale
    /// supports an auto-stop-mode setting and `mode_id` is in range. An
    /// out-of-range `mode_id` yields an empty `CoreOutput`. Wired exactly like
    /// [`set_scale_volume`](Self::set_scale_volume).
    pub fn set_scale_auto_stop(&self, mode_id: u8) -> String {
        json(self.core().set_scale_auto_stop(mode_id))
    }

    /// Build a [`CoreOutput`] (JSON) whose command queries the connected
    /// scale's settings (the scale answers with a `03 0e …` notification).
    ///
    /// Capability-gated: the command is present only when the connected scale
    /// exposes a configurable setting. Empty otherwise. Wired exactly like
    /// [`tare_scale`](Self::tare_scale).
    pub fn query_scale_settings(&self) -> String {
        json(self.core().query_scale_settings())
    }

    /// Write the DE1's steam / hot-water settings. Returns a JSON-encoded
    /// [`CoreOutput`] whose command applies them (with the legacy hot-water
    /// volume override when a scale is connected).
    pub fn set_steam_hotwater_settings(&self, settings: SteamHotWaterSettings) -> String {
        json(self.core().set_steam_hotwater_settings(settings.into()))
    }

    /// Enable or disable steam eco mode (the legacy `eco_steam` setting).
    /// Returns a JSON-encoded [`CoreOutput`].
    pub fn enable_steam_eco_mode(&self, enabled: bool, now_ms: u64) -> String {
        json(self.core().enable_steam_eco_mode(enabled, now_ms))
    }

    /// The standard DE1 profiles Crema ships built in, as a JSON array string.
    ///
    /// Each element is a `Profile`; the shell deserializes the array into its
    /// own profile type, consistent with the rest of the JSON-string surface.
    pub fn builtin_profiles_json(&self) -> String {
        self.core().builtin_profiles_json()
    }
}

/// Serialize a [`CoreOutput`] to JSON for the shell.
///
/// `CoreOutput` is a flat structure of enums, numbers, strings and vectors, so
/// serialization is infallible in practice — a failure would be a bug here.
fn json(output: CoreOutput) -> String {
    output
        .to_json()
        .expect("CoreOutput is plain data and always serializes")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn on_notification_returns_core_output_json() {
        let bridge = CremaBridge::new();
        let json = bridge.on_notification(NotificationSource::De1State, vec![4, 5], 1_000);
        assert!(json.contains("\"events\""));
        assert!(json.contains("\"ShotStarted\""));
    }

    #[test]
    fn request_machine_state_produces_a_write_command() {
        let bridge = CremaBridge::new();
        let json = bridge.request_machine_state(MachineRequest::Idle);
        assert!(json.contains("\"commands\""));
        assert!(json.contains("WriteCharacteristic"));
    }

    #[test]
    fn connect_scale_identifies_a_known_scale() {
        let bridge = CremaBridge::new();
        assert_eq!(
            bridge.connect_scale("BOOKOO_SC".to_owned()),
            Some("Bookoo".to_owned())
        );
        assert_eq!(bridge.connect_scale("Not A Scale".to_owned()), None);
    }

    #[test]
    fn scale_capabilities_is_none_without_a_connected_scale() {
        let bridge = CremaBridge::new();
        assert!(bridge.scale_capabilities().is_none());
    }

    #[test]
    fn scale_capabilities_reports_a_bookoo_as_first_class() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.scale_capabilities().expect("a connected scale");
        let caps: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert_eq!(caps["volume"]["min"], 0);
        assert_eq!(caps["volume"]["max"], 3);
        assert_eq!(caps["reports_flow"], true);
        assert_eq!(caps["reports_timer"], true);
    }

    #[test]
    fn scale_capabilities_reports_a_weight_only_scale_as_having_none() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("Decent Scale ABC".to_owned());
        let json = bridge.scale_capabilities().expect("a connected scale");
        let caps: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(caps["volume"].is_null());
    }

    #[test]
    fn set_scale_volume_produces_a_write_scale_command_for_a_capable_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.set_scale_volume(3);
        assert!(json.contains("\"commands\""));
        assert!(json.contains("WriteScale"));
    }

    #[test]
    fn set_scale_volume_produces_no_command_for_a_weight_only_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("Decent Scale ABC".to_owned());
        let json = bridge.set_scale_volume(3);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(parsed["commands"].as_array().unwrap().is_empty());
    }

    #[test]
    fn scale_capabilities_reports_modes_for_a_bookoo() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.scale_capabilities().expect("a connected scale");
        let caps: serde_json::Value = serde_json::from_str(&json).unwrap();
        let modes = caps["modes"].as_array().expect("a modes array");
        assert_eq!(modes.len(), 3);
        assert_eq!(modes[0]["id"], 0);
        assert_eq!(modes[0]["name"], "Flow Rate");
    }

    #[test]
    fn set_scale_standby_minutes_produces_a_write_scale_command_for_a_capable_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.set_scale_standby_minutes(15);
        assert!(json.contains("WriteScale"));
    }

    #[test]
    fn set_scale_flow_smoothing_produces_a_write_scale_command_for_a_capable_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.set_scale_flow_smoothing(true);
        assert!(json.contains("WriteScale"));
    }

    #[test]
    fn set_scale_anti_mistouch_produces_a_write_scale_command_for_a_capable_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.set_scale_anti_mistouch(false);
        assert!(json.contains("WriteScale"));
    }

    #[test]
    fn set_scale_mode_produces_three_write_scale_commands_for_a_capable_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.set_scale_mode(1);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        // Three mode writes plus the appended 0x0f settings query.
        assert_eq!(parsed["commands"].as_array().unwrap().len(), 4);
    }

    #[test]
    fn set_scale_auto_stop_produces_a_write_scale_command_for_a_capable_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.set_scale_auto_stop(1);
        assert!(json.contains("WriteScale"));
    }

    #[test]
    fn set_scale_auto_stop_produces_no_command_for_an_out_of_range_mode_id() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.set_scale_auto_stop(9);
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(parsed["commands"].as_array().unwrap().is_empty());
    }

    #[test]
    fn query_scale_settings_produces_a_write_scale_command_for_a_capable_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("BOOKOO_SC".to_owned());
        let json = bridge.query_scale_settings();
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        let commands = parsed["commands"].as_array().unwrap();
        assert_eq!(commands.len(), 1);
        assert_eq!(commands[0]["type"], "WriteScale");
    }

    #[test]
    fn query_scale_settings_produces_no_command_for_a_weight_only_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("Decent Scale ABC".to_owned());
        let json = bridge.query_scale_settings();
        let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
        assert!(parsed["commands"].as_array().unwrap().is_empty());
    }

    #[test]
    fn scale_config_methods_produce_no_command_for_a_weight_only_scale() {
        let bridge = CremaBridge::new();
        bridge.connect_scale("Decent Scale ABC".to_owned());
        for json in [
            bridge.set_scale_standby_minutes(15),
            bridge.set_scale_flow_smoothing(true),
            bridge.set_scale_anti_mistouch(true),
            bridge.set_scale_mode(0),
            bridge.set_scale_auto_stop(0),
        ] {
            let parsed: serde_json::Value = serde_json::from_str(&json).unwrap();
            assert!(parsed["commands"].as_array().unwrap().is_empty());
        }
    }

    /// A `SteamHotWaterSettings` with representative values.
    fn steam_settings() -> SteamHotWaterSettings {
        SteamHotWaterSettings {
            steam_flags: 0,
            steam_temp_c: 150.0,
            steam_timeout_s: 120.0,
            hot_water_temp_c: 85.0,
            hot_water_volume_ml: 50.0,
            hot_water_timeout_s: 30.0,
            espresso_volume_ml: 36.0,
            group_temp_c: 92.0,
        }
    }

    #[test]
    fn set_steam_hotwater_settings_produces_a_write_command() {
        let bridge = CremaBridge::new();
        let json = bridge.set_steam_hotwater_settings(steam_settings());
        assert!(json.contains("\"commands\""));
        assert!(json.contains("WriteCharacteristic"));
        assert!(json.contains("De1ShotSettings"));
    }

    #[test]
    fn enable_steam_eco_mode_returns_core_output_json() {
        let bridge = CremaBridge::new();
        bridge.set_steam_hotwater_settings(steam_settings());
        bridge.enable_steam_eco_mode(true, 0);
        // After the idle delay a tick engages eco mode and rewrites the target.
        let json = bridge.on_tick(600_000);
        assert!(json.contains("SteamEcoModeChanged"));
    }

    #[test]
    fn builtin_profiles_json_returns_a_profile_array() {
        let bridge = CremaBridge::new();
        let json = bridge.builtin_profiles_json();
        assert!(json.starts_with('['));
        assert!(json.contains("\"steps\""));
    }

    #[test]
    fn machine_request_maps_to_the_expected_states() {
        assert_eq!(
            MachineState::from(MachineRequest::Flush),
            MachineState::HotWaterRinse
        );
        assert_eq!(
            MachineState::from(MachineRequest::Descale),
            MachineState::Descale
        );
        assert_eq!(
            MachineState::from(MachineRequest::Clean),
            MachineState::Clean
        );
    }

    /// Every `NotificationSource` the FFI enum can name — used to fuzz the
    /// bridge against malformed input on every characteristic.
    fn every_source() -> [NotificationSource; 5] {
        [
            NotificationSource::De1State,
            NotificationSource::De1ShotSample,
            NotificationSource::ScaleWeight,
            NotificationSource::ScaleCommand,
            NotificationSource::De1WaterLevels,
        ]
    }

    #[test]
    fn on_notification_does_not_panic_on_an_empty_slice() {
        for source in every_source() {
            let bridge = CremaBridge::new();
            // A scale is connected so the ScaleWeight decode path is exercised
            // rather than being skipped for want of a scale.
            bridge.connect_scale("BOOKOO_SC".to_owned());
            let out = bridge.on_notification(source, Vec::new(), 1_000);
            // The bridge must always return a well-formed CoreOutput envelope.
            let parsed: serde_json::Value =
                serde_json::from_str(&out).expect("bridge returned malformed JSON");
            assert!(parsed.get("events").is_some());
            assert!(parsed.get("commands").is_some());
        }
    }

    #[test]
    fn on_notification_does_not_panic_on_garbage_bytes() {
        let garbage = vec![0xFF, 0x00, 0xAB, 0xCD, 0xEF, 0x13, 0x37];
        for source in every_source() {
            let bridge = CremaBridge::new();
            bridge.connect_scale("BOOKOO_SC".to_owned());
            let out = bridge.on_notification(source, garbage.clone(), 2_000);
            let parsed: serde_json::Value =
                serde_json::from_str(&out).expect("bridge returned malformed JSON");
            assert!(parsed["events"].is_array());
        }
    }

    #[test]
    fn on_notification_reports_a_decode_error_for_a_truncated_state_packet() {
        let bridge = CremaBridge::new();
        // A one-byte StateInfo packet cannot be decoded — the bridge must
        // surface a DecodeError event, not panic or drop the input silently.
        let out = bridge.on_notification(NotificationSource::De1State, vec![0x01], 1_000);
        assert!(out.contains("DecodeError"));
    }

    #[test]
    fn on_notification_reports_a_decode_error_for_a_truncated_water_levels_packet() {
        let bridge = CremaBridge::new();
        let out = bridge.on_notification(NotificationSource::De1WaterLevels, vec![0x00], 1_000);
        assert!(out.contains("DecodeError"));
    }
}
