//! # de1-ffi
//!
//! The UniFFI bridge: exposes [`de1_app::CremaCore`] to the Android (Kotlin)
//! shell. The bridge is deliberately thin — it wraps the core behind a mutex
//! and serializes the rich [`CoreOutput`](de1_app::CoreOutput) to JSON (the
//! "Option S" encoding from `docs/08-ffi-and-web-scope.md`). Inputs are simple
//! typed values UniFFI marshals natively.
//!
//! `unsafe` is unavoidable here — UniFFI generates the `extern "C"` FFI
//! scaffolding — which is why this crate opts out of the workspace's
//! `unsafe_code = "forbid"` lint (see `Cargo.toml`).

use std::sync::{Mutex, MutexGuard};

use de1_app::{CoreOutput, CremaCore, Source};
use de1_protocol::MachineState;

uniffi::setup_scaffolding!();

/// Which BLE characteristic an incoming notification came from — mirrors
/// [`de1_app::Source`] across the FFI boundary.
#[derive(uniffi::Enum)]
pub enum NotificationSource {
    /// The DE1 machine state / substate characteristic.
    De1State,
    /// The DE1 shot-telemetry characteristic.
    De1ShotSample,
    /// The connected scale's weight notification.
    ScaleWeight,
    /// The DE1 water-tank level characteristic.
    De1WaterLevels,
}

impl From<NotificationSource> for Source {
    fn from(source: NotificationSource) -> Source {
        match source {
            NotificationSource::De1State => Source::De1State,
            NotificationSource::De1ShotSample => Source::De1ShotSample,
            NotificationSource::ScaleWeight => Source::ScaleWeight,
            NotificationSource::De1WaterLevels => Source::De1WaterLevels,
        }
    }
}

/// A machine state the shell can ask the DE1 to enter.
#[derive(uniffi::Enum)]
pub enum MachineRequest {
    /// Go to sleep.
    Sleep,
    /// Return to idle — also stops a running shot and wakes from sleep.
    Idle,
    /// Start an espresso shot.
    Espresso,
    /// Start steam.
    Steam,
    /// Start hot water.
    HotWater,
    /// Start a group-head flush / rinse.
    Flush,
    /// Start a descale cycle.
    Descale,
    /// Start a cleaning cycle.
    Clean,
    /// Advance to the next espresso frame.
    SkipToNext,
}

impl From<MachineRequest> for MachineState {
    fn from(request: MachineRequest) -> MachineState {
        match request {
            MachineRequest::Sleep => MachineState::Sleep,
            MachineRequest::Idle => MachineState::Idle,
            MachineRequest::Espresso => MachineState::Espresso,
            MachineRequest::Steam => MachineState::Steam,
            MachineRequest::HotWater => MachineState::HotWater,
            MachineRequest::Flush => MachineState::HotWaterRinse,
            MachineRequest::Descale => MachineState::Descale,
            MachineRequest::Clean => MachineState::Clean,
            MachineRequest::SkipToNext => MachineState::SkipToNext,
        }
    }
}

/// The Crema core, exposed to the Kotlin shell.
///
/// Methods that produce a [`CoreOutput`] return it as a JSON string; the shell
/// deserializes it into types generated by `typeshare`. Other methods take and
/// return plain scalars.
#[derive(uniffi::Object)]
pub struct CremaBridge {
    inner: Mutex<CremaCore>,
}

impl CremaBridge {
    /// Lock the wrapped core. The mutex is poisoned only by a panic inside a
    /// core method; the core does not panic, so this never fails in practice.
    fn core(&self) -> MutexGuard<'_, CremaCore> {
        self.inner.lock().expect("CremaCore mutex poisoned")
    }
}

impl Default for CremaBridge {
    fn default() -> CremaBridge {
        CremaBridge::new()
    }
}

#[uniffi::export]
impl CremaBridge {
    /// Create a core in the idle state.
    #[uniffi::constructor]
    pub fn new() -> CremaBridge {
        CremaBridge {
            inner: Mutex::new(CremaCore::new()),
        }
    }

    /// Feed a raw GATT notification. Returns a JSON-encoded [`CoreOutput`].
    pub fn on_notification(
        &self,
        source: NotificationSource,
        data: Vec<u8>,
        now_ms: u64,
    ) -> String {
        json(self.core().on_notification(source.into(), &data, now_ms))
    }

    /// Feed a periodic clock tick. Returns a JSON-encoded [`CoreOutput`].
    pub fn on_tick(&self, now_ms: u64) -> String {
        json(self.core().on_tick(now_ms))
    }

    /// Discard all session state — e.g. on disconnect.
    pub fn reset(&self) {
        self.core().reset();
    }

    /// Identify and connect a scale from its BLE advertised name. Returns
    /// whether the name matched a supported scale.
    pub fn connect_scale(&self, advertised_name: String) -> bool {
        self.core().connect_scale(&advertised_name)
    }

    /// Arm automatic shot-stop at a weight (grams), volume (mL), and/or
    /// max-shot-time (seconds) target.
    pub fn arm_auto_stop(
        &self,
        weight_g: Option<f32>,
        volume_ml: Option<f32>,
        max_time: Option<f32>,
    ) {
        self.core().arm_auto_stop(weight_g, volume_ml, max_time);
    }

    /// Disarm automatic shot-stop.
    pub fn disarm_auto_stop(&self) {
        self.core().disarm_auto_stop();
    }

    /// Build a [`CoreOutput`] (JSON) whose command asks the DE1 to enter
    /// `state`.
    pub fn request_machine_state(&self, state: MachineRequest) -> String {
        json(self.core().request_machine_state(state.into()))
    }

    /// Build a [`CoreOutput`] (JSON) whose command tares the connected scale.
    pub fn tare_scale(&self) -> String {
        json(self.core().tare_scale())
    }
}

/// Serialize a [`CoreOutput`] to JSON for the shell.
///
/// `CoreOutput` is a flat structure of enums, numbers, strings and vectors, so
/// serialization is infallible in practice — a failure would be a bug here.
fn json(output: CoreOutput) -> String {
    output
        .to_json()
        .expect("CoreOutput is plain data and always serializes")
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn on_notification_returns_core_output_json() {
        let bridge = CremaBridge::new();
        let json = bridge.on_notification(NotificationSource::De1State, vec![4, 5], 1_000);
        assert!(json.contains("\"events\""));
        assert!(json.contains("\"ShotStarted\""));
    }

    #[test]
    fn request_machine_state_produces_a_write_command() {
        let bridge = CremaBridge::new();
        let json = bridge.request_machine_state(MachineRequest::Idle);
        assert!(json.contains("\"commands\""));
        assert!(json.contains("WriteCharacteristic"));
    }

    #[test]
    fn connect_scale_identifies_a_known_scale() {
        let bridge = CremaBridge::new();
        assert!(bridge.connect_scale("BOOKOO_SC".to_owned()));
        assert!(!bridge.connect_scale("Not A Scale".to_owned()));
    }

    #[test]
    fn machine_request_maps_to_the_expected_states() {
        assert_eq!(
            MachineState::from(MachineRequest::Flush),
            MachineState::HotWaterRinse
        );
        assert_eq!(
            MachineState::from(MachineRequest::Descale),
            MachineState::Descale
        );
        assert_eq!(
            MachineState::from(MachineRequest::Clean),
            MachineState::Clean
        );
    }
}
