//! Built-in espresso profiles — "batteries included".
//!
//! Crema ships every standard profile from the legacy DE1 tablet app
//! ([de1app](https://github.com/decentespresso/de1app)) as a built-in Crema
//! [`Profile`], stored in Crema's **native** format.
//!
//! The upstream `*.tcl` profile files were each run once through
//! [`import_legacy_tcl`](crate::import_legacy_tcl) and the resulting
//! [`Profile`]s serialized into a single JSON array,
//! `de1-domain/profiles/builtin.json` (see the `README.md` there for origin,
//! license, and how to regenerate). That file is embedded into the crate at
//! compile time with [`include_str!`] — a build-time read, not runtime I/O, so
//! the core stays sans-IO. The built-in path no longer touches the legacy Tcl
//! importer; `import_legacy_tcl` remains for users importing their own legacy
//! profiles.
//!
//! The single public accessor, [`builtin_profiles`], is **infallible**: it
//! never returns a [`Result`] and never panics into the caller. The embedded
//! JSON is parsed once on first access and memoized for the process lifetime.
//! A parse failure would yield an empty list rather than a panic; the
//! `builtin_profiles_all_load` test guarantees that never happens — the whole
//! embedded corpus deserializes and assembles.

use std::sync::OnceLock;

use crate::profile::Profile;

/// The built-in profiles in Crema's native format, embedded at compile time.
///
/// A JSON array of [`Profile`], generated by converting the de1app standard
/// `*.tcl` profiles via [`import_legacy_tcl`](crate::import_legacy_tcl).
const BUILTIN_JSON: &str = include_str!("../profiles/builtin.json");

/// The parsed built-in profiles, memoized on first access.
static BUILTIN: OnceLock<Vec<Profile>> = OnceLock::new();

/// The number of built-in profiles Crema ships — every standard de1app
/// profile (88), plus "Adaptive v2", which de1app main replaced with
/// "Adaptive v3" in the same file (`best_practice.tcl`, de1app 1a61f9b4);
/// Crema keeps both, as decaid (78bebb54) and Decenza (add46044) do.
///
/// Equal to [`builtin_profiles`]`.len()`; the `builtin_profiles_ships_the_full_corpus`
/// test pins the two together.
pub const BUILTIN_PROFILE_COUNT: usize = 89;

/// Every standard DE1 profile, as a built-in Crema [`Profile`].
///
/// The embedded `builtin.json` is deserialized once and the result is cached
/// for the rest of the process. The returned slice is in a stable order (the
/// source `*.tcl` files sorted by file name at generation time).
///
/// This accessor takes no [`Result`]: `builtin.json` is a compile-time-embedded
/// asset, so a parse failure is a build/source bug, not a runtime condition.
///
/// RS5/RS1: it must not `expect`/panic, though — this runs behind the wasm + ffi
/// bridges, where a panic aborts the wasm module and poisons the ffi mutex. A
/// broken asset can never reach the field anyway: the `builtin_profiles_all_load`
/// test asserts the corpus parses non-empty, so the build fails first. So on the
/// unreachable parse error degrade to an empty corpus rather than crashing the
/// shell at the boundary.
pub fn builtin_profiles() -> &'static [Profile] {
    BUILTIN.get_or_init(|| serde_json::from_str(BUILTIN_JSON).unwrap_or_default())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_profiles_all_load() {
        // The embedded JSON must deserialize into a non-empty profile list.
        let profiles = builtin_profiles();
        assert!(
            !profiles.is_empty(),
            "builtin.json failed to deserialize into any profiles",
        );
    }

    #[test]
    fn builtin_profiles_ships_the_full_corpus() {
        // All 88 de1app standard profiles (Adaptive v3 among them) plus the
        // kept Adaptive v2.
        assert_eq!(builtin_profiles().len(), BUILTIN_PROFILE_COUNT);
    }

    #[test]
    fn builtin_profiles_all_assemble() {
        // Every built-in profile must assemble into protocol packets, i.e. be
        // uploadable to a DE1.
        for profile in builtin_profiles() {
            profile
                .assemble()
                .unwrap_or_else(|e| panic!("profile {:?} failed to assemble: {e}", profile.title));
        }
    }

    #[test]
    fn builtin_profiles_all_have_a_title_and_steps() {
        for profile in builtin_profiles() {
            assert!(
                !profile.title.trim().is_empty(),
                "a built-in profile has an empty title",
            );
            assert!(
                !profile.steps.is_empty(),
                "built-in profile {:?} has no steps",
                profile.title,
            );
        }
    }

    #[test]
    fn builtin_profiles_all_have_a_uuid_v7_id() {
        // Every built-in must carry a pre-generated UUID v7 — the
        // `gen-builtin-ids` binary fills `builtin.json` once and the
        // values survive every subsequent build. The shell consumes
        // these IDs as the stable URL key, so a missing or malformed
        // entry would silently break navigation.
        for profile in builtin_profiles() {
            assert!(
                is_uuid_v7(&profile.id),
                "built-in profile {:?} has invalid id {:?} (expected UUID v7)",
                profile.title,
                profile.id,
            );
        }
    }

    /// Match the 36-char dashed UUID v7 form
    /// (`^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`).
    /// Kept here as a local helper so the builtin-corpus assertion does
    /// not pull in a regex dependency.
    fn is_uuid_v7(id: &str) -> bool {
        let bytes = id.as_bytes();
        if bytes.len() != 36 {
            return false;
        }
        for &i in &[8, 13, 18, 23] {
            if bytes[i] != b'-' {
                return false;
            }
        }
        if bytes[14] != b'7' {
            return false;
        }
        if !matches!(bytes[19], b'8' | b'9' | b'a' | b'b') {
            return false;
        }
        bytes.iter().enumerate().all(|(i, &b)| {
            if i == 8 || i == 13 || i == 18 || i == 23 {
                b == b'-'
            } else {
                b.is_ascii_digit() || (b'a'..=b'f').contains(&b)
            }
        })
    }

    /// The built-in with this title.
    fn builtin(title: &str) -> &'static Profile {
        builtin_profiles()
            .iter()
            .find(|p| p.title == title)
            .unwrap_or_else(|| panic!("no built-in titled {title:?}"))
    }

    #[test]
    fn builtin_preinfusion_counts_and_volumes_match_de1app() {
        // (title, preinfuse_step_count, max_total_volume_ml), as de1app's own
        // pressure_to_advanced_list / flow_to_advanced_list compute them
        // (run under tclsh against de1app main; see
        // .scratch/upstream-review-2026-10/builtin-diff.md).
        let expected: &[(&str, u8, u16)] = &[
            // settings_2a: preinfusion frames + forced rises.
            ("Default", 4, 36),
            ("Best overall pressure profile", 3, 36),
            ("Classic Italian espresso", 3, 36),
            ("Gentle and sweet", 3, 36),
            ("Traditional lever machine", 3, 36),
            ("Low pressure lever machine at 6 bar", 2, 36),
            ("E61 espresso machine", 2, 0),
            ("Steam only", 2, 30),
            ("GHC/manual pressure control", 1, 0),
            // settings_2b: preinfusion frames only.
            ("Flow profile for straight espresso", 2, 36),
            ("Hybrid pour over espresso", 1, 0),
            ("Preinfuse then 45ml of water", 1, 36),
            ("GHC/manual flow control", 0, 0),
            // settings_2c: the TCL's explicit count, 0 included.
            ("Londonium", 2, 0),
            ("Cremina lever machine", 0, 0),
            ("Espresso Forge Dark", 0, 0),
            ("Filter 2.1", 0, 0),
            ("Blooming Allongé", 0, 180),
        ];
        for &(title, count, volume) in expected {
            let p = builtin(title);
            assert_eq!(
                p.preinfuse_step_count, count,
                "{title}: preinfuse_step_count"
            );
            assert_eq!(p.max_total_volume_ml, volume, "{title}: volume");
            // The count reaches the DE1 header unchanged.
            assert_eq!(
                p.assemble().unwrap().header.preinfuse_frame_count,
                count,
                "{title}: header"
            );
        }
    }

    #[test]
    fn builtin_step_weights_come_from_the_tcl() {
        // A-Flow's Infuse exits on weight (issue 11); so does Filter 2.0's
        // flat-flow step. Every other built-in step has none.
        let expected: &[(&str, &str, f32)] = &[
            ("A-Flow / default-dark", "Infuse", 2.0),
            ("A-Flow / default-like-dflow", "Infuse", 4.0),
            ("A-Flow / default-medium", "Infuse", 3.6),
            ("A-Flow / default-very-dark", "Infuse", 2.0),
            ("Filter 2.0", "flat flow", 150.0),
        ];
        for &(title, step, grams) in expected {
            let p = builtin(title);
            let s = p.steps.iter().find(|s| s.name == step).unwrap();
            assert_eq!(s.weight, Some(grams), "{title} / {step}");
        }
        let with_weights = builtin_profiles()
            .iter()
            .flat_map(|p| p.steps.iter())
            .filter(|s| s.weight.is_some())
            .count();
        assert_eq!(with_weights, expected.len());
    }

    #[test]
    fn adaptive_v3_ships_alongside_v2() {
        // de1app 1a61f9b4: Pressurize exits at 7.7 bar (v2: 8.8) and the
        // extraction limiter is 8.6 bar (v2: 9.5); otherwise the same frames.
        let v2 = builtin("Adaptive v2");
        let v3 = builtin("Adaptive v3");
        assert_ne!(v2.id, v3.id);
        assert_eq!(v3.steps.len(), v2.steps.len());
        let pressurize = |p: &Profile| p.steps[4].exit.unwrap().threshold;
        assert_eq!(pressurize(v2), 8.8);
        assert_eq!(pressurize(v3), 7.7);
        for i in [5, 6] {
            assert_eq!(v2.steps[i].limiter.unwrap().value, 9.5);
            assert_eq!(v3.steps[i].limiter.unwrap().value, 8.6);
        }
        assert_eq!(v3.preinfuse_step_count, 3);
        assert_eq!(v3.max_total_volume_ml, 36);
    }

    #[test]
    fn builtin_profiles_is_memoized() {
        // Two calls return the very same cached slice.
        let first = builtin_profiles();
        let second = builtin_profiles();
        assert!(std::ptr::eq(first, second));
    }

    #[test]
    fn builtin_profiles_round_trip_through_serde() {
        // Each built-in profile serializes and deserializes losslessly, which
        // is what the JSON-string FFI surface relies on.
        for profile in builtin_profiles() {
            let json = serde_json::to_string(profile).expect("serialize");
            let back: Profile = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(&back, profile);
        }
    }
}
