//! Built-in espresso profiles — "batteries included".
//!
//! Crema ships every standard profile from the legacy DE1 tablet app
//! ([de1app](https://github.com/decentespresso/de1app)) as a built-in Crema
//! [`Profile`], stored in Crema's **native** format.
//!
//! The upstream `*.tcl` profile files were each run once through
//! [`import_legacy_tcl`](crate::import_legacy_tcl) and the resulting
//! [`Profile`]s serialized into a single JSON array,
//! `de1-domain/profiles/builtin.json` (see the `README.md` there for origin,
//! license, and how to regenerate). That file is embedded into the crate at
//! compile time with [`include_str!`] — a build-time read, not runtime I/O, so
//! the core stays sans-IO. The built-in path no longer touches the legacy Tcl
//! importer; `import_legacy_tcl` remains for users importing their own legacy
//! profiles.
//!
//! The single public accessor, [`builtin_profiles`], is **infallible**: it
//! never returns a [`Result`] and never panics into the caller. The embedded
//! JSON is parsed once on first access and memoized for the process lifetime.
//! A parse failure would yield an empty list rather than a panic; the
//! `builtin_profiles_all_load` test guarantees that never happens — the whole
//! embedded corpus deserializes and assembles.

use std::sync::OnceLock;

use crate::profile::Profile;

/// The built-in profiles in Crema's native format, embedded at compile time.
///
/// A JSON array of [`Profile`], generated by converting the de1app standard
/// `*.tcl` profiles via [`import_legacy_tcl`](crate::import_legacy_tcl).
const BUILTIN_JSON: &str = include_str!("../profiles/builtin.json");

/// The parsed built-in profiles, memoized on first access.
static BUILTIN: OnceLock<Vec<Profile>> = OnceLock::new();

/// The number of built-in profiles Crema ships — every standard de1app
/// profile.
///
/// Equal to [`builtin_profiles`]`.len()`; the `builtin_profiles_ships_the_full_corpus`
/// test pins the two together.
pub const BUILTIN_PROFILE_COUNT: usize = 88;

/// Every standard DE1 profile, as a built-in Crema [`Profile`].
///
/// The embedded `builtin.json` is deserialized once and the result is cached
/// for the rest of the process. The returned slice is in a stable order (the
/// source `*.tcl` files sorted by file name at generation time).
///
/// This accessor takes no [`Result`]: `builtin.json` is a compile-time-embedded
/// asset, so a parse failure is a build/source bug, not a runtime condition.
///
/// RS5/RS1: it must not `expect`/panic, though — this runs behind the wasm + ffi
/// bridges, where a panic aborts the wasm module and poisons the ffi mutex. A
/// broken asset can never reach the field anyway: the `builtin_profiles_all_load`
/// test asserts the corpus parses non-empty, so the build fails first. So on the
/// unreachable parse error degrade to an empty corpus rather than crashing the
/// shell at the boundary.
pub fn builtin_profiles() -> &'static [Profile] {
    BUILTIN.get_or_init(|| serde_json::from_str(BUILTIN_JSON).unwrap_or_default())
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn builtin_profiles_all_load() {
        // The embedded JSON must deserialize into a non-empty profile list.
        let profiles = builtin_profiles();
        assert!(
            !profiles.is_empty(),
            "builtin.json failed to deserialize into any profiles",
        );
    }

    #[test]
    fn builtin_profiles_ships_the_full_corpus() {
        // All 88 vendored de1app standard profiles must be present.
        assert_eq!(builtin_profiles().len(), BUILTIN_PROFILE_COUNT);
    }

    #[test]
    fn builtin_profiles_all_assemble() {
        // Every built-in profile must assemble into protocol packets, i.e. be
        // uploadable to a DE1.
        for profile in builtin_profiles() {
            profile
                .assemble()
                .unwrap_or_else(|e| panic!("profile {:?} failed to assemble: {e}", profile.title));
        }
    }

    #[test]
    fn builtin_profiles_all_have_a_title_and_steps() {
        for profile in builtin_profiles() {
            assert!(
                !profile.title.trim().is_empty(),
                "a built-in profile has an empty title",
            );
            assert!(
                !profile.steps.is_empty(),
                "built-in profile {:?} has no steps",
                profile.title,
            );
        }
    }

    #[test]
    fn builtin_profiles_all_have_a_uuid_v7_id() {
        // Every built-in must carry a pre-generated UUID v7 — the
        // `gen-builtin-ids` binary fills `builtin.json` once and the
        // values survive every subsequent build. The shell consumes
        // these IDs as the stable URL key, so a missing or malformed
        // entry would silently break navigation.
        for profile in builtin_profiles() {
            assert!(
                is_uuid_v7(&profile.id),
                "built-in profile {:?} has invalid id {:?} (expected UUID v7)",
                profile.title,
                profile.id,
            );
        }
    }

    /// Match the 36-char dashed UUID v7 form
    /// (`^[0-9a-f]{8}-[0-9a-f]{4}-7[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$`).
    /// Kept here as a local helper so the builtin-corpus assertion does
    /// not pull in a regex dependency.
    fn is_uuid_v7(id: &str) -> bool {
        let bytes = id.as_bytes();
        if bytes.len() != 36 {
            return false;
        }
        for &i in &[8, 13, 18, 23] {
            if bytes[i] != b'-' {
                return false;
            }
        }
        if bytes[14] != b'7' {
            return false;
        }
        if !matches!(bytes[19], b'8' | b'9' | b'a' | b'b') {
            return false;
        }
        bytes.iter().enumerate().all(|(i, &b)| {
            if i == 8 || i == 13 || i == 18 || i == 23 {
                b == b'-'
            } else {
                b.is_ascii_digit() || (b'a'..=b'f').contains(&b)
            }
        })
    }

    #[test]
    fn builtin_profiles_is_memoized() {
        // Two calls return the very same cached slice.
        let first = builtin_profiles();
        let second = builtin_profiles();
        assert!(std::ptr::eq(first, second));
    }

    #[test]
    fn builtin_profiles_round_trip_through_serde() {
        // Each built-in profile serializes and deserializes losslessly, which
        // is what the JSON-string FFI surface relies on.
        for profile in builtin_profiles() {
            let json = serde_json::to_string(profile).expect("serialize");
            let back: Profile = serde_json::from_str(&json).expect("deserialize");
            assert_eq!(&back, profile);
        }
    }
}
