/**
 * Generated by typeshare 1.13.4
 */

package coffee.crema.core

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/// Whether a bag of coffee is a single-origin lot or a blend. `None` =
/// unknown / unset. Serialises as the lowercase wire string
/// (`"single"` / `"blend"`) to match the TS shell's typed string union.
@Serializable
enum class BeanMix(val string: String) {
	/// A single-origin lot (one farm / region / process).
	@SerialName("single")
	Single("single"),
	/// A blend of two or more components.
	@SerialName("blend")
	Blend("blend"),
}

/// Whether a bag is roasted for espresso, filter, or both. `None` on the
/// owning [`Bean`] = unset; the value never serialises as `"unknown"`
/// (the user picks one of the three or leaves it blank). Lowercase wire
/// strings match the TS shell convention.
/// 
/// Imported from Beanconqueror's `bean_roasting_type` field, which uses
/// the same three categories plus an `Unknown` sentinel that we map to
/// `None` on the bag.
@Serializable
enum class BeanRoastType(val string: String) {
	/// Roasted for espresso pulls — typically a darker development.
	@SerialName("espresso")
	Espresso("espresso"),
	/// Roasted for filter / pour-over.
	@SerialName("filter")
	Filter("filter"),
	/// Roasted to work for both espresso and filter (industry term).
	@SerialName("omni")
	Omni("omni"),
}

/// Origin metadata for a bag — country, region, farm, and the rest of
/// the upstream provenance fields. All optional: a fresh bean's origin
/// starts empty and the user fills in whatever the bag label shows.
/// Mirrors Visualizer's CoffeeBag origin fields so the sync mapping is
/// 1:1.
@Serializable
data class BeanOrigin (
	/// Country of origin — `"Ethiopia"`, `"Ethiopia / Colombia"` for a blend.
	val country: String? = null,
	/// Region within the country — `"Yirgacheffe"`, `"Nyeri"`.
	val region: String? = null,
	/// Farm name — `"Hambela Estate"`.
	val farm: String? = null,
	/// Farmer / producer name — `"Tarekech Geleta"`.
	val farmer: String? = null,
	/// Cultivar / variety — `"Geisha"`, `"SL28 / SL34"`.
	val variety: String? = null,
	/// Elevation, free text — `"1900-2100 masl"`. Free-form because real
	/// bags inconsistently report m / masl / ft / a range / a single.
	val elevation: String? = null,
	/// Process — `"Washed"`, `"Natural"`, `"Anaerobic"`. Free-form for the
	/// same reason as `elevation`.
	val processing: String? = null,
	/// Harvest time — `"2024 Spring"`, `"October 2024"`.
	val harvest_time: String? = null
)

/// One bag of coffee — a row in the bean library. This is
/// the central entity: shots reference one by id, and a snapshot
/// ([`ShotBean`]) is frozen onto each completed shot. The core owns the
/// shape so every shell (web, Android, future iOS) consumes the same
/// type via `#[typeshare]`.
/// 
/// CRUD lives in the shell — the core stays sans-IO and only defines
/// the shape, the conversion helpers and the pure classifiers. A fresh
/// bag is built via [`Bean::new`]; further edits ride on plain field
/// assignment (the shell store is responsible for `updated_at` bumps
/// and persistence).
@Serializable
data class Bean (
	/// Stable id — `"bean:<uuid>"`. The shell mints this on create.
	val id: String,
	/// Bean name — e.g. `"Geisha Esmeralda Lot 3"`. **Required.**
	val name: String,
	/// FK into the roaster directory. `None` for a bag whose roaster was
	/// not recorded; the shell may opportunistically promote the
	/// roaster name from import to a proper [`Roaster`] row.
	val roaster_id: String? = null,
	/// ISO `yyyy-mm-dd` roast date.
	val roasted_on: String? = null,
	/// ISO `yyyy-mm-dd` opened-on date. Crema-only — drives the
	/// staleness signal alongside `roasted_on`.
	val opened_on: String? = null,
	/// ISO `yyyy-mm-dd` frozen-on date. Drives the freshness math's
	/// freeze-pause: a frozen bag's freshness counter is the days
	/// between `roasted_on` and `frozen_on`, paused while frozen.
	val frozen_on: String? = null,
	/// ISO `yyyy-mm-dd` defrosted-on date. Resumes the freshness
	/// counter from `defrosted_on`.
	val defrosted_on: String? = null,
	/// Roast level on Visualizer's 1..10 scale. The shell typically
	/// inputs via a 3-band quick-set (light=1, medium=5, dark=10) and
	/// uses [`roast_band`] to bucket back into the band word.
	val roast_level: UByte? = null,
	/// Single-origin vs blend. `None` = not classified.
	val mix: BeanMix? = null,
	/// What the bag was roasted for — espresso, filter, or omni. `None`
	/// when the user hasn't picked. `#[serde(default)]` so older Bean
	/// records (pre-this-field) deserialise cleanly. Imported from
	/// Beanconqueror's `bean_roasting_type` (its `Unknown` value maps
	/// to `None`).
	val roast_type: BeanRoastType? = null,
	/// Decaf flag — `false` by default.
	val decaf: Boolean,
	/// Provenance metadata. Empty struct by default.
	val origin: BeanOrigin,
	/// Bag size in grams — `0.0` when unknown.
	val bag_size_g: Float,
	/// Remaining grams in the bag — auto-debited per shot when the
	/// shell enables `Track bag remaining weight`. `0.0` when unknown.
	val remaining_g: Float,
	/// Quality score — free text per Visualizer (`"88"`, `"A-"`).
	val quality_score: String,
	/// Tasting notes — multi-line free text.
	val tasting_notes: String,
	/// User star rating 0..5; `0` = unrated.
	val rating: UByte,
	/// Where the bag was bought — `"Counter Culture · Durham"`.
	val place_of_purchase: String? = null,
	/// URL to buy again — Visualizer / roaster / store link.
	val url: String? = null,
	/// Free-form notes (not the tasting box).
	val notes: String,
	/// Pinned to the brew-page bean picker strip.
	val favourite: Boolean,
	/// Unix epoch ms when the bag was archived; `None` = active.
	val archived_at: Long? = null,
	/// Bean-scoped grinder name — `"Niche Zero"`. Bean-scoped because a
	/// grind setting only means something paired with the grinder it
	/// was measured on.
	val grinder: String,
	/// Bean-scoped grinder click / setting — `"1.2"`, `"6 + a tooth"`.
	val grinder_setting: String,
	/// Free-form user tags — e.g. `"daily-driver"`, `"comp"`, `"experimental"`.
	/// Defaults to an empty list. Serialised as `tags` so the JSON contract
	/// matches the [`crate::Profile`] tag pattern.
	val tags: List<String>? = null,
	/// Visualizer `coffee_bag.id` once pushed.
	val visualizer_id: String? = null,
	/// Unix epoch ms when this bag was soft-deleted, or `None` when
	/// active. Required for cross-device sync tombstone propagation:
	/// on the next sync push, the remote row is DELETEd and the local
	/// tombstone is garbage-collected. Defaults to `None` so older
	/// `Bean` JSON deserialises cleanly.
	val deleted_at: Long? = null,
	/// Beanconqueror `bean.config.uuid` from a Bc import. Tracks
	/// provenance so a re-import skips beans we already know.
	val beanconqueror_id: String? = null,
	/// IndexedDB blob ref for the bag photo, if any.
	val image_ref: String? = null,
	/// Open JSON metadata. The escape valve for fields neither
	/// Visualizer nor Crema model first-class, but that an import
	/// (Beanconqueror) or future feature needs to keep round-tripping.
	/// Serialised as `serde_json::Value` so the wire format is a plain
	/// nested object.
	val metadata: Value,
	/// Unix epoch ms when this bag was created.
	val created_at: Long,
	/// Unix epoch ms when this bag was last updated.
	val updated_at: Long
)

/// Generated type representing the anonymous struct variant `MachineStateChanged` of the `Event` Rust enum
@Serializable
data class EventMachineStateChangedInner (
	/// New top-level machine state.
	val state: MachineState,
	/// New substate within `state`.
	val substate: SubState
)

/// Generated type representing the anonymous struct variant `ShotPhaseChanged` of the `Event` Rust enum
@Serializable
data class EventShotPhaseChangedInner (
	/// The phase now in effect.
	val phase: ShotPhase
)

/// Generated type representing the anonymous struct variant `ShotFrameChanged` of the `Event` Rust enum
@Serializable
data class EventShotFrameChangedInner (
	/// Zero-based frame index.
	val frame: UByte
)

/// Generated type representing the anonymous struct variant `Telemetry` of the `Event` Rust enum
@Serializable
data class EventTelemetryInner (
	/// Milliseconds since the shot began; `0` if no shot is in progress.
	val elapsed: UInt,
	/// Group pressure, bar.
	val group_pressure: Float,
	/// Group flow, ml/s.
	val group_flow: Float,
	/// Group-head temperature, °C.
	val head_temp: Float,
	/// Mix temperature, °C — the DE1's blended "group" water temperature.
	val mix_temp: Float,
	/// Steam-heater temperature, °C.
	val steam_temp: Float,
	/// Running shot volume dispensed so far, ml — integrated from the
	/// telemetry flow stream against the DE1's `sample_time` ticks
	/// (BLE-jitter-immune when the line-frequency is known, host-clock
	/// fallback otherwise). Resets to 0 on every `ShotStarted`.
	val dispensed_volume: Float,
	/// Target group-head temperature, °C — the heater setpoint for the
	/// active frame. Legacy "Goal temperature" curve on the live shot
	/// chart (`de1_de1.tcl:540` maps `goal_temperature ← SetHeadTemp`).
	val set_head_temp: Float,
	/// Target group pressure, bar — the pump pressure setpoint for the
	/// active frame. Legacy "Goal pressure" curve.
	val set_group_pressure: Float,
	/// Target group flow, ml/s — the pump flow setpoint for the active
	/// frame. Legacy "Goal flow" curve.
	val set_group_flow: Float,
	/// Puck resistance — `group_pressure / group_flow²`, the
	/// de1app/DSx derived "resistance" metric (the R4 read-path).
	/// `None` when group flow is too low to divide by meaningfully —
	/// the near-zero-flow region produces noisy spikes that have no
	/// useful interpretation. Units are `bar / (ml/s)²`. Surfaced on
	/// the event itself so every shell consumes the same value
	/// (previously each shell duplicated the formula + threshold).
	val resistance: Float? = null,
	/// Scale-derived puck resistance — `group_pressure /
	/// weight_flow²` where `weight_flow` is the scale's mass-flow
	/// rate (g/s). The truer extraction signal during the pour
	/// because it measures what exits the puck into the cup, not
	/// what the pump pushes in. `None` when no scale is paired (no
	/// estimate yet), when the scale's flow is below the resistance
	/// floor, or when any input is non-finite. Units: `bar / (g/s)²`.
	/// The chart prefers this over [`Self::resistance`] per-sample
	/// (with the DE1-flow value as fallback when this is `None`)
	/// so shots with and without a scale render coherently. The
	/// legacy de1app TCL computes the same metric — see
	/// `de1plus/gui.tcl:3414-3416`.
	val resistance_weight: Float? = null
)

/// Generated type representing the anonymous struct variant `ScaleReading` of the `Event` Rust enum
@Serializable
data class EventScaleReadingInner (
	/// Robust current weight, grams.
	val weight: Float,
	/// Robust mass-flow rate, grams per second — the core's own estimate
	/// from the weight series, available for every supported scale.
	val flow: Float,
	/// The scale's own native mass-flow rate, grams per second, when the
	/// scale reports one (the Bookoo does); `None` otherwise. Distinct
	/// from the core-computed `flow` — surfaced as raw data.
	val device_flow: Float? = null,
	/// The scale's own built-in-timer reading, milliseconds, when the
	/// scale reports one (the Bookoo does); `None` otherwise.
	val device_timer: UInt? = null,
	/// The scale's live beeper-volume setting `0..=5`, when the scale
	/// echoes its settings in the weight notification (the Bookoo does);
	/// `None` otherwise. Lets a settings control display the real value.
	val device_volume: UByte? = null,
	/// The scale's live auto-standby timeout, minutes, when the scale
	/// echoes its settings (the Bookoo does); `None` otherwise.
	val device_standby: UByte? = null,
	/// The scale's live battery charge percentage, when the scale reports
	/// it (the Bookoo does); `None` otherwise.
	val device_battery: UByte? = null,
	/// Whether the scale's flow smoothing is on, when the scale echoes its
	/// settings in the weight notification (the Bookoo does); `None`
	/// otherwise. Lets a settings toggle reflect the real on/off state.
	val device_flow_smoothing: Boolean? = null,
	/// The scale's live auto-stop mode id (`0` = Flow-Stop, `1` =
	/// Cup-Removal), when the scale echoes its settings in the weight
	/// notification (the Bookoo does); `None` otherwise. Lets a settings
	/// selector reflect the real current mode.
	val device_auto_stop: UByte? = null
)

/// Generated type representing the anonymous struct variant `WaterLevel` of the `Event` Rust enum
@Serializable
data class EventWaterLevelInner (
	/// Current tank level, mm — includes the legacy +5 mm sensor correction.
	val level: Float,
	/// Refill threshold, mm; a refill is wanted at or below it.
	val refill_threshold: Float
)

/// Generated type representing the anonymous struct variant `StopTriggered` of the `Event` Rust enum
@Serializable
data class EventStopTriggeredInner (
	/// Why the shot was stopped.
	val reason: StopReason
)

/// Generated type representing the anonymous struct variant `ShotCompleted` of the `Event` Rust enum
@Serializable
data class EventShotCompletedInner (
	/// Total shot duration, milliseconds.
	val duration: UInt,
	/// Number of telemetry samples recorded.
	val sample_count: UInt,
	/// Peak group pressure observed across every Telemetry sample of the
	/// shot, bar. `None` when no telemetry arrived. Computed once at the
	/// core boundary — previously each shell re-iterated the buffered
	/// series for it.
	val peak_pressure: Float? = null,
	/// Peak group-head temperature observed across every Telemetry
	/// sample of the shot, °C. `None` when no telemetry arrived.
	val peak_temp: Float? = null,
	/// Peak scale weight observed across every ScaleReading of the shot,
	/// grams. `None` when no scale was paired (no readings arrived).
	val peak_weight: Float? = null,
	/// The final scale weight observed before the shot ended, grams —
	/// the "shot yield". `None` when no scale was paired (no readings
	/// arrived).
	val final_weight: Float? = null
)

/// Generated type representing the anonymous struct variant `WaterSessionStarted` of the `Event` Rust enum
@Serializable
data class EventWaterSessionStartedInner (
	/// Whether this is a hot-water pour or a flush.
	val kind: WaterSessionKind
)

/// Generated type representing the anonymous struct variant `WaterSessionCompleted` of the `Event` Rust enum
@Serializable
data class EventWaterSessionCompletedInner (
	/// Whether this was a hot-water pour or a flush.
	val kind: WaterSessionKind,
	/// Total session duration, milliseconds.
	val duration: UInt
)

/// Generated type representing the anonymous struct variant `SteamSessionCompleted` of the `Event` Rust enum
@Serializable
data class EventSteamSessionCompletedInner (
	/// Total session duration, milliseconds.
	val duration: UInt,
	/// Number of steam telemetry samples recorded.
	val sample_count: UInt
)

/// Generated type representing the anonymous struct variant `SteamClogSuspected` of the `Event` Rust enum
@Serializable
data class EventSteamClogSuspectedInner (
	/// Which threshold the steam telemetry tripped.
	val reason: SteamClogReason
)

/// Generated type representing the anonymous struct variant `SteamEcoModeChanged` of the `Event` Rust enum
@Serializable
data class EventSteamEcoModeChangedInner (
	/// `true` when the steam target dropped to the lower eco temperature.
	val eco: Boolean
)

/// Generated type representing the anonymous struct variant `ScaleConfig` of the `Event` Rust enum
@Serializable
data class EventScaleConfigInner (
	/// The scale's live anti-mistouch state — `Some` only for a `03 0c`
	/// serial response, `None` for a `03 0e` settings response.
	val anti_mistouch: Boolean? = null,
	/// The scale's active display-mode index (`0` = Flow-Rate, `1` =
	/// Timer, `2` = Auto) — `Some` only for a `03 0e` settings response.
	val active_mode: UByte? = null,
	/// The scale's enabled-modes bitmask (bit `n` set when mode `n` is
	/// enabled) — `Some` only for a `03 0e` settings response.
	val enabled_modes: UByte? = null,
	/// The scale's serial number — `Some` only for a `03 0c` serial
	/// response.
	val serial: String? = null,
	/// The scale's firmware version, encoded `major × 100 + minor × 10 +
	/// patch` (e.g. `141` is firmware 1.4.1) — `Some` only for a `03 0c`
	/// serial response.
	val firmware_version: UShort? = null
)

/// Generated type representing the anonymous struct variant `Firmware` of the `Event` Rust enum
@Serializable
data class EventFirmwareInner (
	/// The BLE-firmware release number.
	val release: Float,
	/// The BLE-firmware commits-since-release count.
	val commits: UShort,
	/// The BLE-firmware API version.
	val api_version: UByte,
	/// A human-readable firmware label, e.g. `"v1.0.142 (API 4)"`.
	val firmware_string: String
)

/// Generated type representing the anonymous struct variant `MmrValue` of the `Event` Rust enum
@Serializable
data class EventMmrValueInner (
	/// Which register this value is for.
	val register: MmrRegister,
	/// The register's raw 32-bit value, little-endian. Some registers are
	/// scaled (e.g. `CalibrationFlowMultiplier` is `int(1000 ×
	/// multiplier)`); the raw word is surfaced and the reader scales it.
	val value: UInt
)

/// Generated type representing the anonymous struct variant `Calibration` of the `Event` Rust enum
@Serializable
data class EventCalibrationInner (
	/// Which sensor the calibration applies to.
	val target: CalTarget,
	/// Whether this is the current (in-use) or the factory calibration —
	/// [`CalCommand::ReadCurrent`] or [`CalCommand::ReadFactory`].
	val command: CalCommand,
	/// The value the DE1's sensor reported at calibration time.
	val de1_reported: Float,
	/// The externally-measured true value the DE1 was calibrated against.
	val measured: Float
)

/// Generated type representing the anonymous struct variant `FirmwareLockoutHit` of the `Event` Rust enum
@Serializable
data class EventFirmwareLockoutHitInner (
	/// Name of the [`CremaCore`](crate::CremaCore) method that was
	/// refused — e.g. `"set_refill_threshold"`.
	val method: String
)

/// Generated type representing the anonymous struct variant `ProfileHeaderRead` of the `Event` Rust enum
@Serializable
data class EventProfileHeaderReadInner (
	/// Total number of frames in the loaded profile.
	val frame_count: UByte,
	/// How many leading frames count as preinfusion.
	val preinfuse_frame_count: UByte,
	/// Minimum pressure allowed in flow-priority frames, bar.
	val minimum_pressure: Float,
	/// Maximum flow allowed in pressure-priority frames, ml/s.
	val maximum_flow: Float
)

/// Generated type representing the anonymous struct variant `ShotSettingsRead` of the `Event` Rust enum
@Serializable
data class EventShotSettingsReadInner (
	/// Target steam temperature, °C.
	val steam_temp: Float,
	/// Steam timeout, seconds.
	val steam_timeout: Float,
	/// Target hot-water temperature, °C.
	val hot_water_temp: Float,
	/// Hot-water volume, ml.
	val hot_water_volume: Float,
	/// Hot-water timeout, seconds.
	val hot_water_timeout: Float,
	/// Espresso target volume, ml.
	val espresso_volume: Float,
	/// Espresso group target temperature, °C.
	val group_temp: Float
)

/// Generated type representing the anonymous struct variant `ProfileUploadStarted` of the `Event` Rust enum
@Serializable
data class EventProfileUploadStartedInner (
	/// Title of the profile being uploaded — propagated for the
	/// shell's UI ("Uploading <title>…") and for the active-profile
	/// tracking that pairs with this event.
	val title: String,
	/// Number of normal frames the profile has.
	val frame_count: UByte,
	/// Number of extension frames (one per step that has a limiter).
	val extension_frame_count: UByte
)

/// Generated type representing the anonymous struct variant `ProfileUploadProgress` of the `Event` Rust enum
@Serializable
data class EventProfileUploadProgressInner (
	/// The step index just acknowledged. For an extension-frame ack
	/// this is the step the extension extends (raw `FrameToWrite` byte
	/// minus 32); for the tail it equals `frame_count`.
	val frame: UByte,
	/// Whether the just-acked write was an extension frame.
	val extension: Boolean,
	/// Total number of acks the upload expects
	/// (`frame_count + extension_count + 1`).
	val total_acks: UShort,
	/// Number of acks received so far, including this one.
	val acks_received: UShort
)

/// Generated type representing the anonymous struct variant `ProfileUploadCompleted` of the `Event` Rust enum
@Serializable
data class EventProfileUploadCompletedInner (
	/// Title of the profile that finished uploading.
	val title: String
)

/// Generated type representing the anonymous struct variant `ProfileUploadFailed` of the `Event` Rust enum
@Serializable
data class EventProfileUploadFailedInner (
	/// Why the upload failed.
	val reason: ProfileUploadFailure
)

/// Generated type representing the anonymous struct variant `DecodeError` of the `Event` Rust enum
@Serializable
data class EventDecodeErrorInner (
	/// Human-readable description of the failure.
	val message: String
)

/// Something the core observed that the UI may want to react to.
/// 
/// Serialized adjacently tagged — a JSON event reads `{"type":"ShotStarted"}`
/// or `{"type":"Telemetry","content":{"elapsed":…}}`.
/// 
/// Numeric fields stay as flat scalars (`u32`, `f32`) so they cross the FFI
/// boundary as plain numbers — `Duration` does not transmit through typeshare
/// to TS / Kotlin. The unit each scalar carries is documented in its
/// doc-comment.
@Serializable
sealed class Event {
	/// The DE1's machine state or substate changed.
	@Serializable
	@SerialName("MachineStateChanged")
	data class MachineStateChanged(val content: EventMachineStateChangedInner): Event()
	/// An espresso shot began.
	@Serializable
	@SerialName("ShotStarted")
	object ShotStarted: Event()
	/// The shot moved to a new phase.
	@Serializable
	@SerialName("ShotPhaseChanged")
	data class ShotPhaseChanged(val content: EventShotPhaseChangedInner): Event()
	/// The DE1 advanced to a new profile frame.
	@Serializable
	@SerialName("ShotFrameChanged")
	data class ShotFrameChanged(val content: EventShotFrameChangedInner): Event()
	/// A telemetry sample arrived from the DE1.
	@Serializable
	@SerialName("Telemetry")
	data class Telemetry(val content: EventTelemetryInner): Event()
	/// A weight reading arrived from the scale, smoothed by the flow estimator.
	@Serializable
	@SerialName("ScaleReading")
	data class ScaleReading(val content: EventScaleReadingInner): Event()
	/// The DE1 reported its water-tank level.
	@Serializable
	@SerialName("WaterLevel")
	data class WaterLevel(val content: EventWaterLevelInner): Event()
	/// Auto-stop decided the shot should end. The accompanying [`Command`]
	/// carries the actual stop write.
	@Serializable
	@SerialName("StopTriggered")
	data class StopTriggered(val content: EventStopTriggeredInner): Event()
	/// The espresso shot finished.
	@Serializable
	@SerialName("ShotCompleted")
	data class ShotCompleted(val content: EventShotCompletedInner): Event()
	/// A hot-water or flush session began (the DE1 entered the `HotWater` or
	/// `HotWaterRinse` state).
	@Serializable
	@SerialName("WaterSessionStarted")
	data class WaterSessionStarted(val content: EventWaterSessionStartedInner): Event()
	/// A hot-water or flush session finished.
	@Serializable
	@SerialName("WaterSessionCompleted")
	data class WaterSessionCompleted(val content: EventWaterSessionCompletedInner): Event()
	/// A steam session began (the DE1 entered the `Steam` state).
	@Serializable
	@SerialName("SteamSessionStarted")
	object SteamSessionStarted: Event()
	/// A steam session finished.
	@Serializable
	@SerialName("SteamSessionCompleted")
	data class SteamSessionCompleted(val content: EventSteamSessionCompletedInner): Event()
	/// The just-finished steam session's telemetry suggests a clogged steam
	/// wand. Accompanies the [`Event::SteamSessionCompleted`] for the session.
	@Serializable
	@SerialName("SteamClogSuspected")
	data class SteamClogSuspected(val content: EventSteamClogSuspectedInner): Event()
	/// Steam eco mode engaged or disengaged. When it changes, an accompanying
	/// [`Command`] rewrites the DE1's steam target temperature.
	@Serializable
	@SerialName("SteamEcoModeChanged")
	data class SteamEcoModeChanged(val content: EventSteamEcoModeChangedInner): Event()
	/// The connected scale stopped reporting weight — no reading has arrived
	/// for roughly a second. Emitted once per stale episode; a fresh reading
	/// re-arms it.
	@Serializable
	@SerialName("ScaleStale")
	object ScaleStale: Event()
	/// The connected scale reported its dynamic configuration on its command
	/// characteristic (the Bookoo's `ff12` channel).
	/// 
	/// The scale answers a serial query (`0x0a`, also echoed after every
	/// anti-mistouch write) with the `anti_mistouch` state plus its `serial`
	/// and `firmware_version`; it answers a settings query (`0x0f`) with the
	/// `active_mode` index and `enabled_modes` bitmask. Any one notification
	/// carries only one response type, so the fields the other response would
	/// fill are `None` — the shell folds in whichever fields are present and
	/// keeps its last value for the rest, the two-way pattern the Bookoo's
	/// weight-stream settings already use.
	@Serializable
	@SerialName("ScaleConfig")
	data class ScaleConfig(val content: EventScaleConfigInner): Event()
	/// The DE1 reported its firmware version (the `Version` characteristic).
	/// Carries the **BLE-block** identity — the primary firmware identity per
	/// the legacy `de1_version_string` (`vars.tcl:3867`). The CPU/FW block is
	/// often all-zero on real DE1s and is not surfaced here; `firmware_string`
	/// appends its values only when the FW block carries a distinct, non-zero
	/// `Sha`.
	@Serializable
	@SerialName("Firmware")
	data class Firmware(val content: EventFirmwareInner): Event()
	/// A DE1 memory-mapped register was read back. Emitted when a
	/// `ReadFromMMR` reply decodes to a register Crema models; one event per
	/// register the reply carries.
	@Serializable
	@SerialName("MmrValue")
	data class MmrValue(val content: EventMmrValueInner): Event()
	/// A DE1 sensor calibration was read back from the `Calibration`
	/// characteristic — the current (in-use) or factory calibration for one
	/// sensor.
	@Serializable
	@SerialName("Calibration")
	data class Calibration(val content: EventCalibrationInner): Event()
	/// A write was refused because a firmware upload is locking out other
	/// writes. v1 carries the lockout guard as a stub
	/// ([`firmware_locks_writes`](crate::CremaCore::firmware_locks_writes))
	/// that always returns `false`; v2 will return `true` for the
	/// `Erase..Verifying` phases of a firmware upload. The event names the
	/// refused method so the shell can show a transient toast.
	@Serializable
	@SerialName("FirmwareLockoutHit")
	data class FirmwareLockoutHit(val content: EventFirmwareLockoutHitInner): Event()
	/// **DORMANT — see [`Source::De1ProfileHeader`].** This
	/// event would carry the DE1's reported `ShotHeader` if the firmware
	/// supported reading the loaded-profile buffer on `cuuid_0F`. It does
	/// not (snoop-verified 2026-05-21), so the BLE shell no longer triggers
	/// the Read and this variant is never emitted in the current code path.
	/// 
	/// Kept for forward-compat — the decode path
	/// ([`CremaCore::handle_profile_header_read`](crate::CremaCore)) and
	/// every consumer (UI, tests) remain in place; flipping the BLE shell
	/// back to issuing a Read is one line in `web/src/lib/ble/de1.ts`.
	@Serializable
	@SerialName("ProfileHeaderRead")
	data class ProfileHeaderRead(val content: EventProfileHeaderReadInner): Event()
	/// The DE1's steam + hot-water + group-temp `ShotSettings` were read,
	/// either at connect-time or in response to a setting change. Mirrors
	/// the legacy de1app's `de1_read_hotwater` flow (`bluetooth.tcl:1707`)
	/// and reaprime's `shotSettings` notify stream.
	@Serializable
	@SerialName("ShotSettingsRead")
	data class ShotSettingsRead(val content: EventShotSettingsReadInner): Event()
	/// A profile upload has begun. Carries the total number of acks the
	/// orchestrator expects (frames + extensions + tail; the header is
	/// not acked separately).
	@Serializable
	@SerialName("ProfileUploadStarted")
	data class ProfileUploadStarted(val content: EventProfileUploadStartedInner): Event()
	/// One profile frame was acknowledged by the DE1.
	@Serializable
	@SerialName("ProfileUploadProgress")
	data class ProfileUploadProgress(val content: EventProfileUploadProgressInner): Event()
	/// The whole profile uploaded successfully — every expected ack
	/// arrived in order. Carries the title for the shell's
	/// active-profile bookkeeping.
	@Serializable
	@SerialName("ProfileUploadCompleted")
	data class ProfileUploadCompleted(val content: EventProfileUploadCompletedInner): Event()
	/// The profile upload failed. The core has discarded its in-progress
	/// state; the shell may retry by calling `upload_profile` again.
	@Serializable
	@SerialName("ProfileUploadFailed")
	data class ProfileUploadFailed(val content: EventProfileUploadFailedInner): Event()
	/// An incoming notification could not be decoded.
	@Serializable
	@SerialName("DecodeError")
	data class DecodeError(val content: EventDecodeErrorInner): Event()
}

/// Generated type representing the anonymous struct variant `WriteCharacteristic` of the `Command` Rust enum
@Serializable
data class CommandWriteCharacteristicInner (
	/// Which characteristic to write.
	val target: WriteTarget,
	/// The bytes to write.
	val data: List<UByte>
)

/// Generated type representing the anonymous struct variant `WriteScale` of the `Command` Rust enum
@Serializable
data class CommandWriteScaleInner (
	/// The bytes to write.
	val data: List<UByte>
)

/// A BLE write the shell should perform on the core's behalf.
/// 
/// The core owns the protocol, so a command carries the exact bytes; the shell
/// only needs a characteristic-UUID map, no protocol logic.
@Serializable
sealed class Command {
	/// Write `data` to a DE1 GATT characteristic.
	@Serializable
	@SerialName("WriteCharacteristic")
	data class WriteCharacteristic(val content: CommandWriteCharacteristicInner): Command()
	/// Write `data` to the connected scale's command characteristic.
	@Serializable
	@SerialName("WriteScale")
	data class WriteScale(val content: CommandWriteScaleInner): Command()
}

/// The result of feeding the core one input: what it observed (`events`) and
/// what it wants the shell to do (`commands`).
/// 
/// `#[non_exhaustive]` so further fields can be added without breaking the
/// bridge crates.
@Serializable
data class CoreOutput (
	/// The events observed, in order.
	val events: List<Event>,
	/// BLE writes the shell should perform, in order.
	val commands: List<Command>
)

/// A slim view onto the shell's `StoredShot`: only the fields the
/// reconcile planner reads. Lets the shell project its full record
/// (web `StoredShot` in `$lib/history/model.ts`, Android equivalent)
/// into a stable cross-shell shape without dragging the rest of the
/// record (`series`, `bean`, `metadata`) through the FFI.
/// 
/// Field names are camelCase on the wire — the JSON shape lines up
/// 1:1 with the web shell's `StoredShot`, so callers can hand a
/// `StoredShot` straight to `JSON.stringify` and `serde_json::from_str`
/// parses it cleanly (extra fields are ignored).
@Serializable
data class LocalShotRef (
	/// Local stable id — `shot:<uuid>` in the web shell.
	val id: String,
	/// Unix epoch ms the shot completed.
	val completedAt: Long,
	/// Total shot duration, milliseconds.
	val duration: Long,
	/// Active profile's name when the shot was pulled, or `null`.
	val profileName: String? = null,
	/// Final scale weight at shot end, grams, or `null`.
	val finalWeight: Float? = null,
	/// Visualizer `shot.id` once uploaded — the binding key. `null` /
	/// missing for an unbound local.
	val visualizerId: String? = null,
	/// Unix epoch ms when this shot was soft-deleted, or `null` / missing
	/// when active. Tombstoned locals must NOT bind to a remote.
	val deletedAt: Long? = null
)

/// A derived maintenance readout — counters, percentages, and due/ok
/// verdicts. Mirrors the TS `MaintenanceReadout`.
@Serializable
data class MaintenanceReadout (
	/// Litres since the last filter change.
	val filterUsedLitres: Double,
	/// Filter capacity remaining, 0–100 %.
	val filterPercent: Double,
	/// Whether the filter still has usable capacity.
	val filterOk: Boolean,
	/// Litres dispensed since the last descale.
	val descaleSinceLitres: Double,
	/// Whether the descale interval has not yet been exceeded.
	val descaleOk: Boolean,
	/// Whole hours since the last clean cycle.
	val cleanSinceHours: Long,
	/// Whether the clean interval has not yet been exceeded.
	val cleanOk: Boolean
)

/// The persisted maintenance state — counters, baselines, and
/// user-set intervals. Mirrors the TS `MaintenanceState`.
@Serializable
data class MaintenanceState (
	/// Total litres of water dispensed, ever — the integrated flow counter.
	val totalLitres: Double,
	/// `total_litres` at the last filter clean.
	val filterBaselineLitres: Double,
	/// `total_litres` at the last descale.
	val descaleBaselineLitres: Double,
	/// Unix epoch ms of the last clean cycle.
	val cleanAtMs: Long,
	/// Unix epoch ms of the last filter clean.
	val filterAtMs: Long,
	/// Unix epoch ms of the last descale.
	val descaleAtMs: Long,
	/// Filter clean-interval threshold, litres.
	val filterCapacityLitres: Double,
	/// Descale interval, litres.
	val descaleIntervalLitres: Double,
	/// Clean cycle interval, hours.
	val cleanIntervalHours: Double
)

/// One selectable display/behaviour mode a scale exposes.
/// 
/// A "first-class" scale (the Bookoo) lets the user switch the active display
/// mode; this descriptor carries each mode's wire `id` and a human-readable
/// `name`, so the shell renders one control per mode without per-model
/// hardcoding. The shell passes the `id` straight back to `set_scale_mode`.
@Serializable
data class ModeInfo (
	/// The mode's wire identifier — passed back unchanged to select this mode.
	val id: UByte,
	/// A human-readable name for the mode, suitable for a button label.
	val name: String
)

/// The inclusive `[min, max]` bounds of a ranged scale setting.
/// 
/// A ranged setting (the beeper volume, the auto-standby timeout) carries its
/// real bounds rather than a bare "supported" flag, so the shell can render a
/// control over `[min, max]` directly — no normalization, no per-model
/// hardcoding. The step is implied `1`: every supported ranged setting takes a
/// whole-number value.
@Serializable
data class RangeCapability (
	/// The smallest value the setting accepts.
	val min: UByte,
	/// The largest value the setting accepts.
	val max: UByte
)

/// Bean snapshot at shot start; nested under [`ReplayMeta::bean`].
/// 
/// All fields optional; absent on the connect-phase prelude, present
/// (in part) on the shell's at-shot-start line.
@Serializable
data class ReplayMetaBean (
	/// Bean type / name (`"Yirgacheffe"`, …).
	val type: String? = null,
	/// Roaster's display name.
	val roaster: String? = null,
	/// ISO `yyyy-mm-dd` roast date.
	val roastedOn: String? = null,
	/// 1..10 roast level.
	val roastLevel: Double? = null,
	/// Free-text tasting / dial notes.
	val notes: String? = null,
	/// Grinder click / setting label.
	val grinderSetting: String? = null
)

/// Merged metadata from one or more `src:"META"` prelude entries.
/// 
/// Every field is optional; META omits any unset field, and the
/// folder leaves every absent field unchanged. Field names are
/// camelCase in the wire / TS / Kotlin shapes; Rust uses snake_case
/// and typeshare renames at the boundary.
@Serializable
data class ReplayMeta (
	/// Scale's BLE advertised name (`"BOOKOO_SC"`, `"ACAIA…"`, …).
	val scaleName: String? = null,
	/// DE1's firmware build number (MMR `FirmwareVersion`).
	val de1FirmwareVersion: Double? = null,
	/// DE1's machine-model identifier (MMR `MachineModel`).
	val de1MachineModel: Double? = null,
	/// DE1's serial number (MMR `SerialNumber`).
	val de1SerialNumber: Double? = null,
	/// Active profile's display name at shot start.
	val profileName: String? = null,
	/// Byte-exact upload payload as lowercase no-separator hex.
	val profileBytesHex: String? = null,
	/// QC yield target at shot start, grams.
	val yieldTarget: Double? = null,
	/// QC brew-temperature override at shot start, °C.
	val brewTemp: Double? = null,
	/// QC pre-infusion target at shot start, seconds.
	val preinfuseTarget: Double? = null,
	/// SAW toggle at shot start.
	val stopOnWeight: Boolean? = null,
	/// Auto-tare toggle at shot start.
	val autoTare: Boolean? = null,
	/// Active bean snapshot at shot start.
	val bean: ReplayMetaBean? = null,
	/// Equipment-level grinder model at shot start.
	val grinderModel: String? = null
)

/// One roastery — a record in the roaster directory. Sparse on
/// purpose, mirroring Visualizer's `RoasterDetail` (which is itself
/// minimal: id + name + website + image). Beanconqueror has no
/// first-class roaster entity — its `bean.roaster` is free text; the
/// shell promotes unique strings into [`Roaster`] rows on import.
@Serializable
data class Roaster (
	/// Stable id — `"roaster:<uuid>"`.
	val id: String,
	/// Roastery name. **Required.**
	val name: String,
	/// Roastery website / store URL.
	val website: String? = null,
	/// Logo / hero image URL. Mirrors Visualizer's `RoasterDetail.image_url`
	/// — round-trips losslessly on sync. Renders as a small thumbnail in
	/// the roaster card and the editor's preview slot.
	val image_url: String? = null,
	/// City — e.g. `"Portland"`. Crema-only; rides in `metadata.crema.city`
	/// on Visualizer round-trip so the wire format stays lossless.
	val city: String? = null,
	/// Country / state / region — free text. Crema-only.
	val country: String? = null,
	/// Free-form notes (private to the user — not pushed to Visualizer).
	val notes: String,
	/// Pointer to the canonical roaster id when this row was tagged as a
	/// duplicate. `None` = this row is itself canonical (or has not been
	/// deduped). Mirrors Visualizer's `RoasterDetail.canonical_roaster_id`
	/// — round-trips directly. Beans pointing at a duplicate are typically
	/// re-pointed at the canonical id on merge.
	val canonical_roaster_id: String? = null,
	/// Visualizer `roaster.id` once pushed.
	val visualizer_id: String? = null,
	/// Unix epoch ms when this roaster was soft-deleted, or `None` when
	/// active. See [`Bean::deleted_at`] for the rationale. Defaults to
	/// `None` so older JSON deserialises cleanly.
	val deleted_at: Long? = null,
	/// Open JSON metadata — escape valve symmetric with [`Bean::metadata`].
	val metadata: Value,
	/// Unix epoch ms.
	val created_at: Long,
	/// Unix epoch ms.
	val updated_at: Long
)

/// What a connected scale can do, beyond reporting a bare weight.
/// 
/// Crema is **capability-driven, never device-driven**: the app reads this
/// descriptor and conditionally enables features, so it never branches on a
/// concrete scale model. A plain weight-only scale has every field absent /
/// `false` / empty; a "first-class" scale (the Bookoo today) sets the
/// capabilities it supports.
/// 
/// Ranged settings carry their real `[min, max]` bounds as a
/// [`RangeCapability`] (`None` = the scale does not expose that setting), so
/// the shell renders a control over the actual range. Toggle settings stay a
/// plain `bool` — there is nothing to parameterize. The selectable display
/// modes are a `Vec<ModeInfo>` (empty = no mode support).
/// 
/// `#[non_exhaustive]`: more capabilities are added here as later slices land,
/// without breaking callers — a new field is purely additive.
@Serializable
data class ScaleCapabilities (
	/// The scale reports its own native mass-flow rate in its weight
	/// notification (surfaced as `ScaleReading::flow_g_per_s`).
	val reports_flow: Boolean,
	/// The scale reports its own built-in-timer reading in its weight
	/// notification (surfaced as `ScaleReading::timer_ms`).
	val reports_timer: Boolean,
	/// The bounds of the scale's settable beeper volume — `None` when the
	/// scale's volume is not settable. `min` is the quietest step (`0` =
	/// silent), `max` the loudest.
	val volume: RangeCapability? = null,
	/// The bounds of the scale's auto-standby timeout, in minutes — `None`
	/// when the scale has no configurable auto-standby.
	val standby: RangeCapability? = null,
	/// The scale accepts a command to toggle flow smoothing.
	val flow_smoothing: Boolean,
	/// The scale accepts a command to toggle anti-mistouch.
	val anti_mistouch: Boolean,
	/// The scale accepts a command to select its auto-stop mode (the Bookoo's
	/// flow-stop / cup-removal setting).
	val auto_stop: Boolean,
	/// The selectable display/behaviour modes the scale exposes — empty when
	/// the scale has no switchable modes. Each entry carries the mode's wire
	/// `id` and a display `name`.
	val modes: List<ModeInfo>
)

/// The BLE UUIDs a scale's transport layer needs.
/// 
/// `Clone` but not `Copy`: three string slices (48 bytes) exceed the size
/// where implicit copies are a sensible default.
/// 
/// `#[typeshare]` + serde `Serialize` (behind the `serde` feature): the web
/// shell needs these UUIDs to know which Web Bluetooth characteristics to
/// subscribe to, so they cross the JSON bridge boundary.
@Serializable
data class ScaleUuids (
	/// GATT service UUID.
	val service: String,
	/// Characteristic weight notifications arrive on.
	val weight_notify: String,
	/// Characteristic commands are written to — equal to `weight_notify` for
	/// scales that use a single characteristic for both.
	val command_write: String
)

/// A snapshot of the active bean at the moment a shot was pulled.
/// Frozen onto each [`crate::history::StoredShot`] (in the shell's
/// extended record) so a later rename / archive / delete of the bag
/// does not retroactively rewrite history.
/// 
/// Beanconqueror reads the bean *live* off the brew (`Brew.bean: uuid`,
/// see `Beanconqueror/src/classes/brew/brew.ts:60`). Crema takes the
/// other approach: snapshot wins. A shot recorded under "Onyx Geisha"
/// stays "Onyx Geisha" forever, even if the user later renames the bag.
/// 
/// Holds the strict minimum the History list / detail panel needs to
/// render the shot without re-fetching the bag — the user-facing
/// strings plus the dates that drive the freshness pill.
@Serializable
data class ShotBean (
	/// FK back to the [`Bean`] in the library, if it still exists. The
	/// History row can resolve the link to open the bean detail; an
	/// archived / deleted bean falls back to the snapshot strings.
	val bean_id: String? = null,
	/// Bag name at the time of the shot — `"Geisha Esmeralda Lot 3"`.
	val name: String,
	/// Roaster name at the time of the shot. Not the roaster id — the
	/// id might dangle, but a string survives.
	val roaster_name: String? = null,
	/// ISO `yyyy-mm-dd` roast date at the time of the shot.
	val roasted_on: String? = null,
	/// Roast level (1..10) at the time of the shot.
	val roast_level: UByte? = null
)

/// The fields the planner reads from a remote shot row. Visualizer's
/// API returns a superset; we only care about identity + the de-dup
/// hash inputs + editable annotations. Mirrors the TS `WireShot` in
/// `shot-sync-signatures.ts`. Unix MS (converted at the spec boundary
/// from the spec's unix-sec `clock` / `updated_at`).
/// 
/// `#[serde(default)]` on the optional fields so a shell that omits them
/// deserialises cleanly. The wasm / FFI bridges JSON-marshal this.
@Serializable
data class WireShot (
	/// Visualizer shot id — the remote primary key.
	val id: String,
	/// Shot start timestamp, unix MS (converted from spec's unix-sec `clock`).
	val clock: Long,
	/// Total shot duration, milliseconds.
	val duration_ms: Long,
	/// Display name of the profile pulled.
	val profile_title: String? = null,
	/// Final scale weight at shot end (grams), or `None`.
	val final_weight_g: Float? = null,
	/// Annotations the user has typed remotely.
	val notes: String? = null,
	/// Star rating (0..5), or `None`.
	val rating: Int? = null,
	/// Last server-side update, unix MS (from spec's unix-sec
	/// `updated_at`). Drives LWW conflict resolution.
	val updated_at_ms: Long? = null,
	/// Shot-level tags pulled from the remote — the `tags` array on
	/// `DefaultShotDetail` (Visualizer's native serializer; the
	/// Beanconqueror variant doesn't carry shot tags). These are
	/// mutable metadata, NOT part of the de-dup signature: a remote
	/// re-tagging doesn't change the shot's identity.
	/// 
	/// `#[serde(default)]` so older shells / responses without the
	/// field still deserialise cleanly to an empty Vec.
	val tag_list: List<String>? = null
)

/// What a calibration packet asks the DE1 to do.
/// 
/// `#[non_exhaustive]` so any future firmware-side calibration verb can
/// land here without breaking the FFI surface — this enum is the payload
/// of `Event::Calibration` alongside `CalTarget`.
@Serializable
enum class CalCommand(val string: String) {
	/// Read the calibration currently in use.
	@SerialName("ReadCurrent")
	ReadCurrent("ReadCurrent"),
	/// Write a new calibration.
	@SerialName("Write")
	Write("Write"),
	/// Reset the sensor to its factory calibration.
	@SerialName("ResetToFactory")
	ResetToFactory("ResetToFactory"),
	/// Read the factory calibration.
	@SerialName("ReadFactory")
	ReadFactory("ReadFactory"),
}

/// Which sensor a calibration applies to.
@Serializable
enum class CalTarget(val string: String) {
	/// The flow-rate sensor.
	@SerialName("Flow")
	Flow("Flow"),
	/// The pressure sensor.
	@SerialName("Pressure")
	Pressure("Pressure"),
	/// The temperature sensor.
	@SerialName("Temperature")
	Temperature("Temperature"),
}

/// Generated type representing the anonymous struct variant `UpToDate` of the `FirmwareUpdateStatus` Rust enum
@Serializable
data class FirmwareUpdateStatusUpToDateInner (
	/// The installed build number.
	val installed: UShort
)

/// Generated type representing the anonymous struct variant `UpdateAvailable` of the `FirmwareUpdateStatus` Rust enum
@Serializable
data class FirmwareUpdateStatusUpdateAvailableInner (
	/// The installed build number.
	val installed: UShort,
	/// The latest build Crema knows about.
	val latest: UShort
)

/// Generated type representing the anonymous struct variant `NewerInstalled` of the `FirmwareUpdateStatus` Rust enum
@Serializable
data class FirmwareUpdateStatusNewerInstalledInner (
	/// The installed build number.
	val installed: UShort,
	/// The (older) build Crema knows about.
	val latest: UShort
)

/// What the firmware-update check found.
/// 
/// `#[non_exhaustive]` so we can grow the enum (e.g. a future "checking…" /
/// "fetched-from-manifest" variant) without breaking shell `match`es.
@Serializable
sealed class FirmwareUpdateStatus {
	/// No DE1 connected, or MMR register `0x800010` (FirmwareVersion) has not
	/// yet been read. The shell should render "Connect a DE1 to check" or
	/// similar.
	@Serializable
	@SerialName("Unknown")
	object Unknown: FirmwareUpdateStatus()
	/// The installed build matches [`LATEST_KNOWN_FIRMWARE_BUILD`].
	@Serializable
	@SerialName("UpToDate")
	data class UpToDate(val content: FirmwareUpdateStatusUpToDateInner): FirmwareUpdateStatus()
	/// The installed build is older than [`LATEST_KNOWN_FIRMWARE_BUILD`].
	@Serializable
	@SerialName("UpdateAvailable")
	data class UpdateAvailable(val content: FirmwareUpdateStatusUpdateAvailableInner): FirmwareUpdateStatus()
	/// The installed build is newer than [`LATEST_KNOWN_FIRMWARE_BUILD`] —
	/// likely the user updated through the legacy de1app since this Crema
	/// build shipped. Informational; no action needed.
	@Serializable
	@SerialName("NewerInstalled")
	data class NewerInstalled(val content: FirmwareUpdateStatusNewerInstalledInner): FirmwareUpdateStatus()
}

/// DE1 top-level machine state. Discriminants match the firmware `MachineState`
/// enum (see protocol §4.1).
@Serializable
enum class MachineState(val string: String) {
	@SerialName("Sleep")
	Sleep("Sleep"),
	@SerialName("GoingToSleep")
	GoingToSleep("GoingToSleep"),
	@SerialName("Idle")
	Idle("Idle"),
	@SerialName("Busy")
	Busy("Busy"),
	@SerialName("Espresso")
	Espresso("Espresso"),
	@SerialName("Steam")
	Steam("Steam"),
	@SerialName("HotWater")
	HotWater("HotWater"),
	@SerialName("ShortCal")
	ShortCal("ShortCal"),
	@SerialName("SelfTest")
	SelfTest("SelfTest"),
	@SerialName("LongCal")
	LongCal("LongCal"),
	@SerialName("Descale")
	Descale("Descale"),
	@SerialName("FatalError")
	FatalError("FatalError"),
	@SerialName("Init")
	Init("Init"),
	/// A "no-op" value, used in RequestedState to mean "no change".
	@SerialName("NoRequest")
	NoRequest("NoRequest"),
	/// A command value: advance to the next espresso frame.
	@SerialName("SkipToNext")
	SkipToNext("SkipToNext"),
	@SerialName("HotWaterRinse")
	HotWaterRinse("HotWaterRinse"),
	@SerialName("SteamRinse")
	SteamRinse("SteamRinse"),
	@SerialName("Refill")
	Refill("Refill"),
	@SerialName("Clean")
	Clean("Clean"),
	@SerialName("InBootLoader")
	InBootLoader("InBootLoader"),
	@SerialName("AirPurge")
	AirPurge("AirPurge"),
	/// Scheduled-wake idle; firmware v1293 and later only.
	@SerialName("SchedIdle")
	SchedIdle("SchedIdle"),
}

/// Known MMR register addresses.
/// 
/// This covers the registers Crema reads or writes.
/// [`address`](Self::address) gives the raw 24-bit address to pass to
/// [`read_request`] / [`write_request`].
@Serializable
enum class MmrRegister(val string: String) {
	/// CPU-board revision, encoded `cpu_board_version × 1000` (e.g. raw
	/// `1100` → PCB v1.1, raw `1300` → PCB v1.3). Read at connect time
	/// in the legacy de1app via `get_3_mmr_cpuboard_machinemodel_firmwareversion`.
	@SerialName("CpuBoardVersion")
	CpuBoardVersion("CpuBoardVersion"),
	/// Machine model identifier — `0 = Unset / unknown`, `1 = DE1`,
	/// `2 = DE1+`, `3 = DE1PRO`, `4 = DE1XL`, `5 = DE1CAFE`, `6 = DE1XXL`,
	/// `7 = DE1XXXL`. The legacy app uses this to gate model-specific
	/// settings (e.g. the cup-warmer surface on Bengle hardware).
	@SerialName("MachineModel")
	MachineModel("MachineModel"),
	/// Firmware build number.
	@SerialName("FirmwareVersion")
	FirmwareVersion("FirmwareVersion"),
	/// Group Head Controller info bitmask (bit 0: present, bit 1: active).
	@SerialName("GhcInfo")
	GhcInfo("GhcInfo"),
	/// Tank desired water-temperature threshold, °C.
	@SerialName("TankTempThreshold")
	TankTempThreshold("TankTempThreshold"),
	/// Fan-on temperature threshold, °C.
	@SerialName("FanThreshold")
	FanThreshold("FanThreshold"),
	/// Machine serial number.
	@SerialName("SerialNumber")
	SerialNumber("SerialNumber"),
	/// Steam flow rate.
	@SerialName("SteamFlow")
	SteamFlow("SteamFlow"),
	/// Refill-kit presence.
	@SerialName("RefillKit")
	RefillKit("RefillKit"),
	/// Flush flow rate.
	@SerialName("FlushFlowRate")
	FlushFlowRate("FlushFlowRate"),
	/// Flush water target temperature, °C — the temperature the DE1
	/// holds while a group-flush cycle runs. Wire value is `°C × 10`
	/// (so 950 = 95.0 °C). Modelled by reaprime
	/// (`de1.models.dart:flushTemp` at `0x00803844`, 4-byte slot,
	/// `readScale: 0.1`); the legacy de1app TCL has no equivalent.
	@SerialName("FlushTemp")
	FlushTemp("FlushTemp"),
	/// Hot-water flow rate.
	@SerialName("HotWaterFlowRate")
	HotWaterFlowRate("HotWaterFlowRate"),
	/// Hot-water dispense phase-1 flow rate.
	@SerialName("Phase1FlowRate")
	Phase1FlowRate("Phase1FlowRate"),
	/// Hot-water dispense phase-2 flow rate.
	@SerialName("Phase2FlowRate")
	Phase2FlowRate("Phase2FlowRate"),
	/// Hot-water idle temperature, °C.
	@SerialName("HotWaterIdleTemp")
	HotWaterIdleTemp("HotWaterIdleTemp"),
	/// Group head control mode.
	@SerialName("GhcMode")
	GhcMode("GhcMode"),
	/// Seconds of high-flow steam at the start of a steam cycle.
	@SerialName("SteamHighFlowStart")
	SteamHighFlowStart("SteamHighFlowStart"),
	/// Mains heater voltage.
	@SerialName("HeaterVoltage")
	HeaterVoltage("HeaterVoltage"),
	/// Espresso warmup timeout.
	@SerialName("EspressoWarmupTimeout")
	EspressoWarmupTimeout("EspressoWarmupTimeout"),
	/// Calibration flow multiplier (`int(1000 * multiplier)`).
	@SerialName("CalibrationFlowMultiplier")
	CalibrationFlowMultiplier("CalibrationFlowMultiplier"),
	/// Flush timeout (`int(10 * seconds)`).
	@SerialName("FlushTimeout")
	FlushTimeout("FlushTimeout"),
	/// USB charger on (1 = tablet USB charging enabled).
	@SerialName("UsbChargerOn")
	UsbChargerOn("UsbChargerOn"),
	/// Feature-flag bitmask (e.g. the `UserNotPresent` flag).
	@SerialName("FeatureFlags")
	FeatureFlags("FeatureFlags"),
	/// Whether the user is currently present at the machine. The legacy app
	/// writes `1` when the user touches the screen so the firmware does not
	/// sleep on inactivity. **Distinct register from [`FeatureFlags`]** — the
	/// legacy `de1_comms.tcl` writes to two separate addresses; the firmware
	/// MMR map is not openly published but the legacy source treats them as
	/// unrelated registers.
	@SerialName("UserPresent")
	UserPresent("UserPresent"),
	/// Steam two-tap stop register — the second `tap` of the
	/// double-tap-to-stop steam UX (`heater_tweaks`).
	@SerialName("SteamTwoTapStop")
	SteamTwoTapStop("SteamTwoTapStop"),
	/// Cup-warmer temperature (Bengle models only).
	@SerialName("CupWarmerTemp")
	CupWarmerTemp("CupWarmerTemp"),
}

/// Generated type representing the anonymous struct variant `TooManySteps` of the `ProfileUploadFailure` Rust enum
@Serializable
data class ProfileUploadFailureTooManyStepsInner (
	/// How many steps the rejected profile had.
	val count: UInt
)

/// Generated type representing the anonymous struct variant `UnexpectedAck` of the `ProfileUploadFailure` Rust enum
@Serializable
data class ProfileUploadFailureUnexpectedAckInner (
	/// The `FrameToWrite` byte the core expected next, raw (`≥ 32` for
	/// an expected extension ack, `== frame_count` for the tail).
	val expected: UByte,
	/// The `FrameToWrite` byte the ack actually carried.
	val got: UByte
)

/// Generated type representing the anonymous struct variant `AckTimeout` of the `ProfileUploadFailure` Rust enum
@Serializable
data class ProfileUploadFailureAckTimeoutInner (
	/// The `FrameToWrite` byte the core was waiting for when the
	/// timeout fired.
	val awaiting: UByte
)

/// Generated type representing the anonymous struct variant `Internal` of the `ProfileUploadFailure` Rust enum
@Serializable
data class ProfileUploadFailureInternalInner (
	/// Human-readable `Display` of the underlying error.
	val message: String
)

/// Why a profile upload failed.
/// 
/// `#[non_exhaustive]` so additional categories (e.g. a firmware-side
/// "shot in progress" rejection signalled through some future cuuid_10
/// packet) can be added without breaking the FFI surface.
@Serializable
sealed class ProfileUploadFailure {
	/// The profile had no steps.
	@Serializable
	@SerialName("Empty")
	object Empty: ProfileUploadFailure()
	/// The profile had more than 32 steps.
	@Serializable
	@SerialName("TooManySteps")
	data class TooManySteps(val details: ProfileUploadFailureTooManyStepsInner): ProfileUploadFailure()
	/// A frame ack arrived for a frame number the orchestrator did not
	/// expect — either out-of-order or for a step the profile does not have.
	@Serializable
	@SerialName("UnexpectedAck")
	data class UnexpectedAck(val details: ProfileUploadFailureUnexpectedAckInner): ProfileUploadFailure()
	/// No ack arrived within
	/// [`PROFILE_UPLOAD_ACK_TIMEOUT`](crate::PROFILE_UPLOAD_ACK_TIMEOUT) of
	/// the most recent ack (or upload start, for the first ack).
	@Serializable
	@SerialName("AckTimeout")
	data class AckTimeout(val details: ProfileUploadFailureAckTimeoutInner): ProfileUploadFailure()
	/// The shell called
	/// [`cancel_profile_upload`](crate::CremaCore::cancel_profile_upload)
	/// mid-upload.
	@Serializable
	@SerialName("Aborted")
	object Aborted: ProfileUploadFailure()
	/// An unexpected [`AppError`] variant — the bridge couldn't classify it.
	/// The `message` carries the `AppError`'s `Display` output so the shell
	/// can surface it in a toast / log without losing the underlying cause.
	/// 
	/// Previously such variants were silently coerced to
	/// [`ProfileUploadFailure::Empty`], misclassifying real failures.
	@Serializable
	@SerialName("Internal")
	data class Internal(val details: ProfileUploadFailureInternalInner): ProfileUploadFailure()
}

/// Where an espresso shot is in its lifecycle.
/// 
/// `#[non_exhaustive]` so additional phases (e.g. a future post-shot
/// "Draining" classification) can be added without breaking the FFI surface —
/// this enum is the payload of `Event::ShotPhaseChanged`.
@Serializable
enum class ShotPhase(val string: String) {
	/// No espresso shot in progress.
	@SerialName("Idle")
	Idle("Idle"),
	/// Heating and stabilising, before flow begins.
	@SerialName("Heating")
	Heating("Heating"),
	/// Preinfusion — wetting the puck at low pressure or flow.
	@SerialName("Preinfusion")
	Preinfusion("Preinfusion"),
	/// The main pour.
	@SerialName("Pouring")
	Pouring("Pouring"),
	/// Ending — flow has stopped and the group is draining.
	@SerialName("Ending")
	Ending("Ending"),
}

/// Why a steam-clog warning was raised — which threshold the telemetry tripped.
/// 
/// `#[non_exhaustive]` so further clog signatures (e.g. a future flow-based
/// detector) can be added without breaking the FFI surface — this enum rides
/// on the `SteamEvent::ClogWarning` payload.
@Serializable
enum class SteamClogReason(val string: String) {
	/// Steam pressure ran too high for too long — a clogged steam wand.
	@SerialName("OverPressure")
	OverPressure("OverPressure"),
	/// Steam temperature ran too hot for too long.
	@SerialName("OverTemperature")
	OverTemperature("OverTemperature"),
}

/// Why [`AutoStop`] decided to end the shot.
/// 
/// `#[non_exhaustive]` so further stop reasons (e.g. a future puck-collapse
/// trigger) can be added without breaking the FFI surface — this enum is the
/// payload of `Event::StopTriggered`.
@Serializable
enum class StopReason(val string: String) {
	/// The weight target (SAW) was reached.
	@SerialName("Weight")
	Weight("Weight"),
	/// The volume target (SAV) was reached.
	@SerialName("Volume")
	Volume("Volume"),
	/// The maximum shot time was reached (legacy `espresso_max_time`).
	@SerialName("MaxTime")
	MaxTime("MaxTime"),
}

/// DE1 substate. Discriminants match the firmware enum (see protocol §4.2):
/// `0..=20` are operational substates, `200..=217` are error codes.
@Serializable
enum class SubState(val string: String) {
	@SerialName("Ready")
	Ready("Ready"),
	@SerialName("Heating")
	Heating("Heating"),
	@SerialName("FinalHeating")
	FinalHeating("FinalHeating"),
	@SerialName("Stabilising")
	Stabilising("Stabilising"),
	@SerialName("Preinfusion")
	Preinfusion("Preinfusion"),
	@SerialName("Pouring")
	Pouring("Pouring"),
	@SerialName("Ending")
	Ending("Ending"),
	@SerialName("Steaming")
	Steaming("Steaming"),
	@SerialName("DescaleInit")
	DescaleInit("DescaleInit"),
	@SerialName("DescaleFillGroup")
	DescaleFillGroup("DescaleFillGroup"),
	@SerialName("DescaleReturn")
	DescaleReturn("DescaleReturn"),
	@SerialName("DescaleGroup")
	DescaleGroup("DescaleGroup"),
	@SerialName("DescaleSteam")
	DescaleSteam("DescaleSteam"),
	@SerialName("CleanInit")
	CleanInit("CleanInit"),
	@SerialName("CleanFillGroup")
	CleanFillGroup("CleanFillGroup"),
	@SerialName("CleanSoak")
	CleanSoak("CleanSoak"),
	@SerialName("CleanGroup")
	CleanGroup("CleanGroup"),
	@SerialName("Refill")
	Refill("Refill"),
	@SerialName("PausedSteam")
	PausedSteam("PausedSteam"),
	@SerialName("UserNotPresent")
	UserNotPresent("UserNotPresent"),
	@SerialName("Puffing")
	Puffing("Puffing"),
	/// Died with a NaN.
	@SerialName("ErrorNaN")
	ErrorNaN("ErrorNaN"),
	/// Died with an infinity.
	@SerialName("ErrorInf")
	ErrorInf("ErrorInf"),
	/// Generic firmware error.
	@SerialName("ErrorGeneric")
	ErrorGeneric("ErrorGeneric"),
	/// Accelerometer not responding or unlocked.
	@SerialName("ErrorAcc")
	ErrorAcc("ErrorAcc"),
	/// Temperature sensor error.
	@SerialName("ErrorTSensor")
	ErrorTSensor("ErrorTSensor"),
	/// Pressure sensor error.
	@SerialName("ErrorPSensor")
	ErrorPSensor("ErrorPSensor"),
	/// Water-level sensor error.
	@SerialName("ErrorWLevel")
	ErrorWLevel("ErrorWLevel"),
	/// DIP switches forced an error state.
	@SerialName("ErrorDip")
	ErrorDip("ErrorDip"),
	/// An assertion failed.
	@SerialName("ErrorAssertion")
	ErrorAssertion("ErrorAssertion"),
	/// An unsafe value was assigned.
	@SerialName("ErrorUnsafe")
	ErrorUnsafe("ErrorUnsafe"),
	/// An invalid parameter was supplied.
	@SerialName("ErrorInvalidParm")
	ErrorInvalidParm("ErrorInvalidParm"),
	/// External flash access error.
	@SerialName("ErrorFlash")
	ErrorFlash("ErrorFlash"),
	/// Out of memory.
	@SerialName("ErrorOom")
	ErrorOom("ErrorOom"),
	/// A realtime deadline was missed.
	@SerialName("ErrorDeadline")
	ErrorDeadline("ErrorDeadline"),
	/// Current out of bounds (too high).
	@SerialName("ErrorHiCurrent")
	ErrorHiCurrent("ErrorHiCurrent"),
	/// Not enough current.
	@SerialName("ErrorLoCurrent")
	ErrorLoCurrent("ErrorLoCurrent"),
	/// Boot pressure test failed (no water?).
	@SerialName("ErrorBootFill")
	ErrorBootFill("ErrorBootFill"),
	/// Front power switch is off.
	@SerialName("ErrorNoAc")
	ErrorNoAc("ErrorNoAc"),
}

/// Which kind of water-dispensing session the DE1 is running.
/// 
/// `#[non_exhaustive]` so additional session kinds (e.g. a future `SteamRinse`
/// classification) can be added without breaking the FFI surface — this enum
/// rides on every `WaterEvent::Started` payload.
@Serializable
enum class WaterSessionKind(val string: String) {
	/// A hot-water pour (DE1 `HotWater` state).
	@SerialName("HotWater")
	HotWater("HotWater"),
	/// A group-head flush / rinse (DE1 `HotWaterRinse` state).
	@SerialName("Flush")
	Flush("Flush"),
}

/// The user's chosen *display unit* for weight.
/// 
/// Canonical storage is always grams; this enum names the unit the shell
/// surfaces — and crucially, the unit the Decent Scale's on-scale LCD must
/// be told to render. The Decent Scale exposes two LCD-enable wire packets
/// (one with byte `[4] = 0x00` for grams, one with byte `[4] = 0x01` for
/// ounces); the core picks the right packet based on this enum so the
/// on-scale display matches the shell.
/// 
/// `#[typeshare]` + serde: the web shell already keeps a TypeScript
/// `WeightUnit` (`'g' | 'oz'`) in its settings store; carrying the same
/// shape through the bridge means the shell can pass its existing pref
/// straight through without a lookup table.
@Serializable
enum class WeightUnit(val string: String) {
	/// Grams — the canonical unit and the Decent Scale's default LCD mode.
	@SerialName("grams")
	Grams("grams"),
	/// US avoirdupois ounces — the only imperial display alternative.
	@SerialName("ounces")
	Ounces("ounces"),
}

/// A writable DE1 GATT characteristic. The shell maps this to a UUID.
/// 
/// `#[non_exhaustive]`: profile-upload targets arrive later.
@Serializable
enum class WriteTarget(val string: String) {
	/// The DE1 `RequestedState` characteristic (`cuuid_02`).
	@SerialName("De1RequestedState")
	De1RequestedState("De1RequestedState"),
	/// The DE1 steam / hot-water `ShotSettings` characteristic (`cuuid_0B`).
	@SerialName("De1ShotSettings")
	De1ShotSettings("De1ShotSettings"),
	/// The DE1 `ReadFromMMR` characteristic (`cuuid_05`) — an MMR read request
	/// is *written* here; the DE1 answers on the same characteristic's notify.
	@SerialName("De1MmrRequest")
	De1MmrRequest("De1MmrRequest"),
	/// The DE1 `WriteToMMR` characteristic (`cuuid_06`) — an MMR write packet
	/// is sent here. Sibling of [`De1MmrRequest`] on the read side; the two
	/// use distinct UUIDs even though they share a packet layout.
	@SerialName("De1MmrWrite")
	De1MmrWrite("De1MmrWrite"),
	/// The DE1 `Calibration` characteristic (`cuuid_12`) — a calibration read
	/// request is *written* here; the DE1 answers on the same characteristic.
	@SerialName("De1Calibration")
	De1Calibration("De1Calibration"),
	/// The DE1 `WaterLevels` characteristic (`cuuid_11`) — the same
	/// characteristic the DE1 notifies tank level on; a 4-byte
	/// `WaterLevels` packet is *written* here to set the refill threshold.
	@SerialName("De1WaterLevels")
	De1WaterLevels("De1WaterLevels"),
	/// The DE1 `HeaderWrite` characteristic (`cuuid_0F`) — the 5-byte
	/// `ShotHeader` packet is *written* here at the start of a profile
	/// upload.
	@SerialName("De1ProfileHeader")
	De1ProfileHeader("De1ProfileHeader"),
	/// The DE1 `FrameWrite` characteristic (`cuuid_10`) — each 8-byte
	/// frame packet (normal frames, extension frames, and the tail) is
	/// *written* here in upload order during a profile upload. The DE1
	/// echoes each write back as a `Source::De1FrameAck` notification.
	@SerialName("De1ProfileFrame")
	De1ProfileFrame("De1ProfileFrame"),
}

