/*
 Generated by typeshare 1.13.4
*/

/**
 * Something the core observed that the UI may want to react to.
 * 
 * Serialized adjacently tagged — a JSON event reads `{"type":"ShotStarted"}`
 * or `{"type":"Telemetry","content":{"elapsed_ms":…}}`.
 */
export type Event = 
	/** The DE1's machine state or substate changed. */
	| { type: "MachineStateChanged", content: {
	/** New top-level machine state. */
	state: MachineState;
	/** New substate within `state`. */
	substate: SubState;
}}
	/** An espresso shot began. */
	| { type: "ShotStarted", content?: undefined }
	/** The shot moved to a new phase. */
	| { type: "ShotPhaseChanged", content: {
	/** The phase now in effect. */
	phase: ShotPhase;
}}
	/** The DE1 advanced to a new profile frame. */
	| { type: "ShotFrameChanged", content: {
	/** Zero-based frame index. */
	frame: number;
}}
	/** A telemetry sample arrived from the DE1. */
	| { type: "Telemetry", content: {
	/** Milliseconds since the shot began; `0` if no shot is in progress. */
	elapsed_ms: number;
	/** Group pressure, bar. */
	group_pressure: number;
	/** Group flow, mL/s. */
	group_flow: number;
	/** Group-head temperature, °C. */
	head_temp: number;
}}
	/** A weight reading arrived from the scale, smoothed by the flow estimator. */
	| { type: "ScaleReading", content: {
	/** Robust current weight, grams. */
	weight_g: number;
	/**
	 * Robust mass-flow rate, grams per second — the core's own estimate
	 * from the weight series, available for every supported scale.
	 */
	flow_g_per_s: number;
	/**
	 * The scale's own native mass-flow rate, grams per second, when the
	 * scale reports one (the Bookoo does); `None` otherwise. Distinct
	 * from the core-computed `flow_g_per_s` — surfaced as raw data.
	 */
	device_flow_g_per_s?: number;
	/**
	 * The scale's own built-in-timer reading, milliseconds, when the
	 * scale reports one (the Bookoo does); `None` otherwise.
	 */
	device_timer_ms?: number;
	/**
	 * The scale's live beeper-volume setting `0..=5`, when the scale
	 * echoes its settings in the weight notification (the Bookoo does);
	 * `None` otherwise. Lets a settings control display the real value.
	 */
	device_volume?: number;
	/**
	 * The scale's live auto-standby timeout, minutes, when the scale
	 * echoes its settings (the Bookoo does); `None` otherwise.
	 */
	device_standby_minutes?: number;
	/**
	 * The scale's live battery charge percentage, when the scale reports
	 * it (the Bookoo does); `None` otherwise.
	 */
	device_battery_percent?: number;
	/**
	 * Whether the scale's flow smoothing is on, when the scale echoes its
	 * settings in the weight notification (the Bookoo does); `None`
	 * otherwise. Lets a settings toggle reflect the real on/off state.
	 */
	device_flow_smoothing?: boolean;
	/**
	 * The scale's live auto-stop mode id (`0` = Flow-Stop, `1` =
	 * Cup-Removal), when the scale echoes its settings in the weight
	 * notification (the Bookoo does); `None` otherwise. Lets a settings
	 * selector reflect the real current mode.
	 */
	device_auto_stop?: number;
}}
	/** The DE1 reported its water-tank level. */
	| { type: "WaterLevel", content: {
	/** Current tank level, mm — includes the legacy +5 mm sensor correction. */
	level_mm: number;
	/** Refill threshold, mm; a refill is wanted at or below it. */
	refill_threshold_mm: number;
}}
	/**
	 * Auto-stop decided the shot should end. The accompanying [`Command`]
	 * carries the actual stop write.
	 */
	| { type: "StopTriggered", content: {
	/** Why the shot was stopped. */
	reason: StopReason;
}}
	/** The espresso shot finished. */
	| { type: "ShotCompleted", content: {
	/** Total shot duration, milliseconds. */
	duration_ms: number;
	/** Number of telemetry samples recorded. */
	sample_count: number;
}}
	/**
	 * A hot-water or flush session began (the DE1 entered the `HotWater` or
	 * `HotWaterRinse` state).
	 */
	| { type: "WaterSessionStarted", content: {
	/** Whether this is a hot-water pour or a flush. */
	kind: WaterSessionKind;
}}
	/** A hot-water or flush session finished. */
	| { type: "WaterSessionCompleted", content: {
	/** Whether this was a hot-water pour or a flush. */
	kind: WaterSessionKind;
	/** Total session duration, milliseconds. */
	duration_ms: number;
}}
	/** A steam session began (the DE1 entered the `Steam` state). */
	| { type: "SteamSessionStarted", content?: undefined }
	/** A steam session finished. */
	| { type: "SteamSessionCompleted", content: {
	/** Total session duration, milliseconds. */
	duration_ms: number;
	/** Number of steam telemetry samples recorded. */
	sample_count: number;
}}
	/**
	 * The just-finished steam session's telemetry suggests a clogged steam
	 * wand. Accompanies the [`Event::SteamSessionCompleted`] for the session.
	 */
	| { type: "SteamClogSuspected", content: {
	/** Which threshold the steam telemetry tripped. */
	reason: SteamClogReason;
}}
	/**
	 * Steam eco mode engaged or disengaged. When it changes, an accompanying
	 * [`Command`] rewrites the DE1's steam target temperature.
	 */
	| { type: "SteamEcoModeChanged", content: {
	/** `true` when the steam target dropped to the lower eco temperature. */
	eco: boolean;
}}
	/**
	 * The connected scale stopped reporting weight — no reading has arrived
	 * for roughly a second. Emitted once per stale episode; a fresh reading
	 * re-arms it.
	 */
	| { type: "ScaleStale", content?: undefined }
	/**
	 * The connected scale reported its dynamic configuration on its command
	 * characteristic (the Bookoo's `ff12` channel).
	 * 
	 * The scale answers a serial query (`0x0a`, also echoed after every
	 * anti-mistouch write) with the `anti_mistouch` state plus its `serial`
	 * and `firmware_version`; it answers a settings query (`0x0f`) with the
	 * `active_mode` index and `enabled_modes` bitmask. Any one notification
	 * carries only one response type, so the fields the other response would
	 * fill are `None` — the shell folds in whichever fields are present and
	 * keeps its last value for the rest, the two-way pattern the Bookoo's
	 * weight-stream settings already use.
	 */
	| { type: "ScaleConfig", content: {
	/**
	 * The scale's live anti-mistouch state — `Some` only for a `03 0c`
	 * serial response, `None` for a `03 0e` settings response.
	 */
	anti_mistouch?: boolean;
	/**
	 * The scale's active display-mode index (`0` = Flow-Rate, `1` =
	 * Timer, `2` = Auto) — `Some` only for a `03 0e` settings response.
	 */
	active_mode?: number;
	/**
	 * The scale's enabled-modes bitmask (bit `n` set when mode `n` is
	 * enabled) — `Some` only for a `03 0e` settings response.
	 */
	enabled_modes?: number;
	/**
	 * The scale's serial number — `Some` only for a `03 0c` serial
	 * response.
	 */
	serial?: string;
	/**
	 * The scale's firmware version, encoded `major × 100 + minor × 10 +
	 * patch` (e.g. `141` is firmware 1.4.1) — `Some` only for a `03 0c`
	 * serial response.
	 */
	firmware_version?: number;
}}
	/** An incoming notification could not be decoded. */
	| { type: "DecodeError", content: {
	/** Human-readable description of the failure. */
	message: string;
}};

/**
 * A BLE write the shell should perform on the core's behalf.
 * 
 * The core owns the protocol, so a command carries the exact bytes; the shell
 * only needs a characteristic-UUID map, no protocol logic.
 */
export type Command = 
	/** Write `data` to a DE1 GATT characteristic. */
	| { type: "WriteCharacteristic", content: {
	/** Which characteristic to write. */
	target: WriteTarget;
	/** The bytes to write. */
	data: number[];
}}
	/** Write `data` to the connected scale's command characteristic. */
	| { type: "WriteScale", content: {
	/** The bytes to write. */
	data: number[];
}};

/**
 * The result of feeding the core one input: what it observed (`events`) and
 * what it wants the shell to do (`commands`).
 * 
 * `#[non_exhaustive]` so further fields can be added without breaking the
 * bridge crates.
 */
export interface CoreOutput {
	/** The events observed, in order. */
	events: Event[];
	/** BLE writes the shell should perform, in order. */
	commands: Command[];
}

/**
 * One selectable display/behaviour mode a scale exposes.
 * 
 * A "first-class" scale (the Bookoo) lets the user switch the active display
 * mode; this descriptor carries each mode's wire `id` and a human-readable
 * `name`, so the shell renders one control per mode without per-model
 * hardcoding. The shell passes the `id` straight back to `set_scale_mode`.
 */
export interface ModeInfo {
	/** The mode's wire identifier — passed back unchanged to select this mode. */
	id: number;
	/** A human-readable name for the mode, suitable for a button label. */
	name: string;
}

/**
 * The inclusive `[min, max]` bounds of a ranged scale setting.
 * 
 * A ranged setting (the beeper volume, the auto-standby timeout) carries its
 * real bounds rather than a bare "supported" flag, so the shell can render a
 * control over `[min, max]` directly — no normalization, no per-model
 * hardcoding. The step is implied `1`: every supported ranged setting takes a
 * whole-number value.
 */
export interface RangeCapability {
	/** The smallest value the setting accepts. */
	min: number;
	/** The largest value the setting accepts. */
	max: number;
}

/**
 * What a connected scale can do, beyond reporting a bare weight.
 * 
 * Crema is **capability-driven, never device-driven**: the app reads this
 * descriptor and conditionally enables features, so it never branches on a
 * concrete scale model. A plain weight-only scale has every field absent /
 * `false` / empty; a "first-class" scale (the Bookoo today) sets the
 * capabilities it supports.
 * 
 * Ranged settings carry their real `[min, max]` bounds as a
 * [`RangeCapability`] (`None` = the scale does not expose that setting), so
 * the shell renders a control over the actual range. Toggle settings stay a
 * plain `bool` — there is nothing to parameterize. The selectable display
 * modes are a `Vec<ModeInfo>` (empty = no mode support).
 * 
 * `#[non_exhaustive]`: more capabilities are added here as later slices land,
 * without breaking callers — a new field is purely additive.
 */
export interface ScaleCapabilities {
	/**
	 * The scale reports its own native mass-flow rate in its weight
	 * notification (surfaced as `ScaleReading::flow_g_per_s`).
	 */
	reports_flow: boolean;
	/**
	 * The scale reports its own built-in-timer reading in its weight
	 * notification (surfaced as `ScaleReading::timer_ms`).
	 */
	reports_timer: boolean;
	/**
	 * The bounds of the scale's settable beeper volume — `None` when the
	 * scale's volume is not settable. `min` is the quietest step (`0` =
	 * silent), `max` the loudest.
	 */
	volume?: RangeCapability;
	/**
	 * The bounds of the scale's auto-standby timeout, in minutes — `None`
	 * when the scale has no configurable auto-standby.
	 */
	standby_minutes?: RangeCapability;
	/** The scale accepts a command to toggle flow smoothing. */
	flow_smoothing: boolean;
	/** The scale accepts a command to toggle anti-mistouch. */
	anti_mistouch: boolean;
	/**
	 * The scale accepts a command to select its auto-stop mode (the Bookoo's
	 * flow-stop / cup-removal setting).
	 */
	auto_stop: boolean;
	/**
	 * The selectable display/behaviour modes the scale exposes — empty when
	 * the scale has no switchable modes. Each entry carries the mode's wire
	 * `id` and a display `name`.
	 */
	modes: ModeInfo[];
}

/**
 * DE1 top-level machine state. Discriminants match the firmware `MachineState`
 * enum (see protocol §4.1).
 */
export enum MachineState {
	Sleep = "Sleep",
	GoingToSleep = "GoingToSleep",
	Idle = "Idle",
	Busy = "Busy",
	Espresso = "Espresso",
	Steam = "Steam",
	HotWater = "HotWater",
	ShortCal = "ShortCal",
	SelfTest = "SelfTest",
	LongCal = "LongCal",
	Descale = "Descale",
	FatalError = "FatalError",
	Init = "Init",
	/** A "no-op" value, used in RequestedState to mean "no change". */
	NoRequest = "NoRequest",
	/** A command value: advance to the next espresso frame. */
	SkipToNext = "SkipToNext",
	HotWaterRinse = "HotWaterRinse",
	SteamRinse = "SteamRinse",
	Refill = "Refill",
	Clean = "Clean",
	InBootLoader = "InBootLoader",
	AirPurge = "AirPurge",
	/** Scheduled-wake idle; firmware v1293 and later only. */
	SchedIdle = "SchedIdle",
}

/** Where an espresso shot is in its lifecycle. */
export enum ShotPhase {
	/** No espresso shot in progress. */
	Idle = "Idle",
	/** Heating and stabilising, before flow begins. */
	Heating = "Heating",
	/** Preinfusion — wetting the puck at low pressure or flow. */
	Preinfusion = "Preinfusion",
	/** The main pour. */
	Pouring = "Pouring",
	/** Ending — flow has stopped and the group is draining. */
	Ending = "Ending",
}

/** Why a steam-clog warning was raised — which threshold the telemetry tripped. */
export enum SteamClogReason {
	/** Steam pressure ran too high for too long — a clogged steam wand. */
	OverPressure = "OverPressure",
	/** Steam temperature ran too hot for too long. */
	OverTemperature = "OverTemperature",
}

/** Why [`AutoStop`] decided to end the shot. */
export enum StopReason {
	/** The weight target (SAW) was reached. */
	Weight = "Weight",
	/** The volume target (SAV) was reached. */
	Volume = "Volume",
	/** The maximum shot time was reached (legacy `espresso_max_time`). */
	MaxTime = "MaxTime",
}

/**
 * DE1 substate. Discriminants match the firmware enum (see protocol §4.2):
 * `0..=20` are operational substates, `200..=217` are error codes.
 */
export enum SubState {
	Ready = "Ready",
	Heating = "Heating",
	FinalHeating = "FinalHeating",
	Stabilising = "Stabilising",
	Preinfusion = "Preinfusion",
	Pouring = "Pouring",
	Ending = "Ending",
	Steaming = "Steaming",
	DescaleInit = "DescaleInit",
	DescaleFillGroup = "DescaleFillGroup",
	DescaleReturn = "DescaleReturn",
	DescaleGroup = "DescaleGroup",
	DescaleSteam = "DescaleSteam",
	CleanInit = "CleanInit",
	CleanFillGroup = "CleanFillGroup",
	CleanSoak = "CleanSoak",
	CleanGroup = "CleanGroup",
	Refill = "Refill",
	PausedSteam = "PausedSteam",
	UserNotPresent = "UserNotPresent",
	Puffing = "Puffing",
	/** Died with a NaN. */
	ErrorNaN = "ErrorNaN",
	/** Died with an infinity. */
	ErrorInf = "ErrorInf",
	/** Generic firmware error. */
	ErrorGeneric = "ErrorGeneric",
	/** Accelerometer not responding or unlocked. */
	ErrorAcc = "ErrorAcc",
	/** Temperature sensor error. */
	ErrorTSensor = "ErrorTSensor",
	/** Pressure sensor error. */
	ErrorPSensor = "ErrorPSensor",
	/** Water-level sensor error. */
	ErrorWLevel = "ErrorWLevel",
	/** DIP switches forced an error state. */
	ErrorDip = "ErrorDip",
	/** An assertion failed. */
	ErrorAssertion = "ErrorAssertion",
	/** An unsafe value was assigned. */
	ErrorUnsafe = "ErrorUnsafe",
	/** An invalid parameter was supplied. */
	ErrorInvalidParm = "ErrorInvalidParm",
	/** External flash access error. */
	ErrorFlash = "ErrorFlash",
	/** Out of memory. */
	ErrorOom = "ErrorOom",
	/** A realtime deadline was missed. */
	ErrorDeadline = "ErrorDeadline",
	/** Current out of bounds (too high). */
	ErrorHiCurrent = "ErrorHiCurrent",
	/** Not enough current. */
	ErrorLoCurrent = "ErrorLoCurrent",
	/** Boot pressure test failed (no water?). */
	ErrorBootFill = "ErrorBootFill",
	/** Front power switch is off. */
	ErrorNoAc = "ErrorNoAc",
}

/** Which kind of water-dispensing session the DE1 is running. */
export enum WaterSessionKind {
	/** A hot-water pour (DE1 `HotWater` state). */
	HotWater = "HotWater",
	/** A group-head flush / rinse (DE1 `HotWaterRinse` state). */
	Flush = "Flush",
}

/**
 * A writable DE1 GATT characteristic. The shell maps this to a UUID.
 * 
 * `#[non_exhaustive]`: profile-upload and MMR targets arrive later.
 */
export enum WriteTarget {
	/** The DE1 `RequestedState` characteristic (`cuuid_02`). */
	De1RequestedState = "De1RequestedState",
	/** The DE1 steam / hot-water `ShotSettings` characteristic (`cuuid_0B`). */
	De1ShotSettings = "De1ShotSettings",
}

