/*
 Generated by typeshare 1.13.4
*/

/**
 * Something the core observed that the UI may want to react to.
 * 
 * Serialized adjacently tagged — a JSON event reads `{"type":"ShotStarted"}`
 * or `{"type":"Telemetry","content":{"elapsed_ms":…}}`.
 */
export type Event = 
	/** The DE1's machine state or substate changed. */
	| { type: "MachineStateChanged", content: {
	/** New top-level machine state. */
	state: MachineState;
	/** New substate within `state`. */
	substate: SubState;
}}
	/** An espresso shot began. */
	| { type: "ShotStarted", content?: undefined }
	/** The shot moved to a new phase. */
	| { type: "ShotPhaseChanged", content: {
	/** The phase now in effect. */
	phase: ShotPhase;
}}
	/** The DE1 advanced to a new profile frame. */
	| { type: "ShotFrameChanged", content: {
	/** Zero-based frame index. */
	frame: number;
}}
	/** A telemetry sample arrived from the DE1. */
	| { type: "Telemetry", content: {
	/** Milliseconds since the shot began; `0` if no shot is in progress. */
	elapsed_ms: number;
	/** Group pressure, bar. */
	group_pressure: number;
	/** Group flow, mL/s. */
	group_flow: number;
	/** Group-head temperature, °C. */
	head_temp: number;
}}
	/** A weight reading arrived from the scale, smoothed by the flow estimator. */
	| { type: "ScaleReading", content: {
	/** Robust current weight, grams. */
	weight_g: number;
	/** Robust mass-flow rate, grams per second. */
	flow_g_per_s: number;
}}
	/** The DE1 reported its water-tank level. */
	| { type: "WaterLevel", content: {
	/** Current tank level, mm — includes the legacy +5 mm sensor correction. */
	level_mm: number;
	/** Refill threshold, mm; a refill is wanted at or below it. */
	refill_threshold_mm: number;
}}
	/**
	 * Auto-stop decided the shot should end. The accompanying [`Command`]
	 * carries the actual stop write.
	 */
	| { type: "StopTriggered", content: {
	/** Why the shot was stopped. */
	reason: StopReason;
}}
	/** The espresso shot finished. */
	| { type: "ShotCompleted", content: {
	/** Total shot duration, milliseconds. */
	duration_ms: number;
	/** Number of telemetry samples recorded. */
	sample_count: number;
}}
	/**
	 * A hot-water or flush session began (the DE1 entered the `HotWater` or
	 * `HotWaterRinse` state).
	 */
	| { type: "WaterSessionStarted", content: {
	/** Whether this is a hot-water pour or a flush. */
	kind: WaterSessionKind;
}}
	/** A hot-water or flush session finished. */
	| { type: "WaterSessionCompleted", content: {
	/** Whether this was a hot-water pour or a flush. */
	kind: WaterSessionKind;
	/** Total session duration, milliseconds. */
	duration_ms: number;
}}
	/**
	 * The connected scale stopped reporting weight — no reading has arrived
	 * for roughly a second. Emitted once per stale episode; a fresh reading
	 * re-arms it.
	 */
	| { type: "ScaleStale", content?: undefined }
	/** An incoming notification could not be decoded. */
	| { type: "DecodeError", content: {
	/** Human-readable description of the failure. */
	message: string;
}};

/**
 * A BLE write the shell should perform on the core's behalf.
 * 
 * The core owns the protocol, so a command carries the exact bytes; the shell
 * only needs a characteristic-UUID map, no protocol logic.
 */
export type Command = 
	/** Write `data` to a DE1 GATT characteristic. */
	| { type: "WriteCharacteristic", content: {
	/** Which characteristic to write. */
	target: WriteTarget;
	/** The bytes to write. */
	data: number[];
}}
	/** Write `data` to the connected scale's command characteristic. */
	| { type: "WriteScale", content: {
	/** The bytes to write. */
	data: number[];
}};

/**
 * The result of feeding the core one input: what it observed (`events`) and
 * what it wants the shell to do (`commands`).
 * 
 * `#[non_exhaustive]` so further fields can be added without breaking the
 * bridge crates.
 */
export interface CoreOutput {
	/** The events observed, in order. */
	events: Event[];
	/** BLE writes the shell should perform, in order. */
	commands: Command[];
}

/**
 * DE1 top-level machine state. Discriminants match the firmware `MachineState`
 * enum (see protocol §4.1).
 */
export enum MachineState {
	Sleep = "Sleep",
	GoingToSleep = "GoingToSleep",
	Idle = "Idle",
	Busy = "Busy",
	Espresso = "Espresso",
	Steam = "Steam",
	HotWater = "HotWater",
	ShortCal = "ShortCal",
	SelfTest = "SelfTest",
	LongCal = "LongCal",
	Descale = "Descale",
	FatalError = "FatalError",
	Init = "Init",
	/** A "no-op" value, used in RequestedState to mean "no change". */
	NoRequest = "NoRequest",
	/** A command value: advance to the next espresso frame. */
	SkipToNext = "SkipToNext",
	HotWaterRinse = "HotWaterRinse",
	SteamRinse = "SteamRinse",
	Refill = "Refill",
	Clean = "Clean",
	InBootLoader = "InBootLoader",
	AirPurge = "AirPurge",
	/** Scheduled-wake idle; firmware v1293 and later only. */
	SchedIdle = "SchedIdle",
}

/** Where an espresso shot is in its lifecycle. */
export enum ShotPhase {
	/** No espresso shot in progress. */
	Idle = "Idle",
	/** Heating and stabilising, before flow begins. */
	Heating = "Heating",
	/** Preinfusion — wetting the puck at low pressure or flow. */
	Preinfusion = "Preinfusion",
	/** The main pour. */
	Pouring = "Pouring",
	/** Ending — flow has stopped and the group is draining. */
	Ending = "Ending",
}

/** Why [`AutoStop`] decided to end the shot. */
export enum StopReason {
	/** The weight target (SAW) was reached. */
	Weight = "Weight",
	/** The volume target (SAV) was reached. */
	Volume = "Volume",
	/** The maximum shot time was reached (legacy `espresso_max_time`). */
	MaxTime = "MaxTime",
}

/**
 * DE1 substate. Discriminants match the firmware enum (see protocol §4.2):
 * `0..=20` are operational substates, `200..=217` are error codes.
 */
export enum SubState {
	Ready = "Ready",
	Heating = "Heating",
	FinalHeating = "FinalHeating",
	Stabilising = "Stabilising",
	Preinfusion = "Preinfusion",
	Pouring = "Pouring",
	Ending = "Ending",
	Steaming = "Steaming",
	DescaleInit = "DescaleInit",
	DescaleFillGroup = "DescaleFillGroup",
	DescaleReturn = "DescaleReturn",
	DescaleGroup = "DescaleGroup",
	DescaleSteam = "DescaleSteam",
	CleanInit = "CleanInit",
	CleanFillGroup = "CleanFillGroup",
	CleanSoak = "CleanSoak",
	CleanGroup = "CleanGroup",
	Refill = "Refill",
	PausedSteam = "PausedSteam",
	UserNotPresent = "UserNotPresent",
	Puffing = "Puffing",
	/** Died with a NaN. */
	ErrorNaN = "ErrorNaN",
	/** Died with an infinity. */
	ErrorInf = "ErrorInf",
	/** Generic firmware error. */
	ErrorGeneric = "ErrorGeneric",
	/** Accelerometer not responding or unlocked. */
	ErrorAcc = "ErrorAcc",
	/** Temperature sensor error. */
	ErrorTSensor = "ErrorTSensor",
	/** Pressure sensor error. */
	ErrorPSensor = "ErrorPSensor",
	/** Water-level sensor error. */
	ErrorWLevel = "ErrorWLevel",
	/** DIP switches forced an error state. */
	ErrorDip = "ErrorDip",
	/** An assertion failed. */
	ErrorAssertion = "ErrorAssertion",
	/** An unsafe value was assigned. */
	ErrorUnsafe = "ErrorUnsafe",
	/** An invalid parameter was supplied. */
	ErrorInvalidParm = "ErrorInvalidParm",
	/** External flash access error. */
	ErrorFlash = "ErrorFlash",
	/** Out of memory. */
	ErrorOom = "ErrorOom",
	/** A realtime deadline was missed. */
	ErrorDeadline = "ErrorDeadline",
	/** Current out of bounds (too high). */
	ErrorHiCurrent = "ErrorHiCurrent",
	/** Not enough current. */
	ErrorLoCurrent = "ErrorLoCurrent",
	/** Boot pressure test failed (no water?). */
	ErrorBootFill = "ErrorBootFill",
	/** Front power switch is off. */
	ErrorNoAc = "ErrorNoAc",
}

/** Which kind of water-dispensing session the DE1 is running. */
export enum WaterSessionKind {
	/** A hot-water pour (DE1 `HotWater` state). */
	HotWater = "HotWater",
	/** A group-head flush / rinse (DE1 `HotWaterRinse` state). */
	Flush = "Flush",
}

/**
 * A writable DE1 GATT characteristic. The shell maps this to a UUID.
 * 
 * `#[non_exhaustive]`: profile-upload and MMR targets arrive later.
 */
export enum WriteTarget {
	/** The DE1 `RequestedState` characteristic (`cuuid_02`). */
	De1RequestedState = "De1RequestedState",
	/** The DE1 steam / hot-water `ShotSettings` characteristic (`cuuid_0B`). */
	De1ShotSettings = "De1ShotSettings",
}

