/**
 * Generated by typeshare 1.13.4
 */

package coffee.crema.core

import kotlinx.serialization.Serializable
import kotlinx.serialization.SerialName

/// Generated type representing the anonymous struct variant `MachineStateChanged` of the `Event` Rust enum
@Serializable
data class EventMachineStateChangedInner (
	/// New top-level machine state.
	val state: MachineState,
	/// New substate within `state`.
	val substate: SubState
)

/// Generated type representing the anonymous struct variant `ShotPhaseChanged` of the `Event` Rust enum
@Serializable
data class EventShotPhaseChangedInner (
	/// The phase now in effect.
	val phase: ShotPhase
)

/// Generated type representing the anonymous struct variant `ShotFrameChanged` of the `Event` Rust enum
@Serializable
data class EventShotFrameChangedInner (
	/// Zero-based frame index.
	val frame: UByte
)

/// Generated type representing the anonymous struct variant `Telemetry` of the `Event` Rust enum
@Serializable
data class EventTelemetryInner (
	/// Milliseconds since the shot began; `0` if no shot is in progress.
	val elapsed_ms: UInt,
	/// Group pressure, bar.
	val group_pressure: Float,
	/// Group flow, mL/s.
	val group_flow: Float,
	/// Group-head temperature, °C.
	val head_temp: Float
)

/// Generated type representing the anonymous struct variant `ScaleReading` of the `Event` Rust enum
@Serializable
data class EventScaleReadingInner (
	/// Robust current weight, grams.
	val weight_g: Float,
	/// Robust mass-flow rate, grams per second.
	val flow_g_per_s: Float
)

/// Generated type representing the anonymous struct variant `WaterLevel` of the `Event` Rust enum
@Serializable
data class EventWaterLevelInner (
	/// Current tank level, mm — includes the legacy +5 mm sensor correction.
	val level_mm: Float,
	/// Refill threshold, mm; a refill is wanted at or below it.
	val refill_threshold_mm: Float
)

/// Generated type representing the anonymous struct variant `StopTriggered` of the `Event` Rust enum
@Serializable
data class EventStopTriggeredInner (
	/// Why the shot was stopped.
	val reason: StopReason
)

/// Generated type representing the anonymous struct variant `ShotCompleted` of the `Event` Rust enum
@Serializable
data class EventShotCompletedInner (
	/// Total shot duration, milliseconds.
	val duration_ms: UInt,
	/// Number of telemetry samples recorded.
	val sample_count: UInt
)

/// Generated type representing the anonymous struct variant `DecodeError` of the `Event` Rust enum
@Serializable
data class EventDecodeErrorInner (
	/// Human-readable description of the failure.
	val message: String
)

/// Something the core observed that the UI may want to react to.
/// 
/// Serialized adjacently tagged — a JSON event reads `{"type":"ShotStarted"}`
/// or `{"type":"Telemetry","content":{"elapsed_ms":…}}`.
@Serializable
sealed class Event {
	/// The DE1's machine state or substate changed.
	@Serializable
	@SerialName("MachineStateChanged")
	data class MachineStateChanged(val content: EventMachineStateChangedInner): Event()
	/// An espresso shot began.
	@Serializable
	@SerialName("ShotStarted")
	object ShotStarted: Event()
	/// The shot moved to a new phase.
	@Serializable
	@SerialName("ShotPhaseChanged")
	data class ShotPhaseChanged(val content: EventShotPhaseChangedInner): Event()
	/// The DE1 advanced to a new profile frame.
	@Serializable
	@SerialName("ShotFrameChanged")
	data class ShotFrameChanged(val content: EventShotFrameChangedInner): Event()
	/// A telemetry sample arrived from the DE1.
	@Serializable
	@SerialName("Telemetry")
	data class Telemetry(val content: EventTelemetryInner): Event()
	/// A weight reading arrived from the scale, smoothed by the flow estimator.
	@Serializable
	@SerialName("ScaleReading")
	data class ScaleReading(val content: EventScaleReadingInner): Event()
	/// The DE1 reported its water-tank level.
	@Serializable
	@SerialName("WaterLevel")
	data class WaterLevel(val content: EventWaterLevelInner): Event()
	/// Auto-stop decided the shot should end. The accompanying [`Command`]
	/// carries the actual stop write.
	@Serializable
	@SerialName("StopTriggered")
	data class StopTriggered(val content: EventStopTriggeredInner): Event()
	/// The espresso shot finished.
	@Serializable
	@SerialName("ShotCompleted")
	data class ShotCompleted(val content: EventShotCompletedInner): Event()
	/// The connected scale stopped reporting weight — no reading has arrived
	/// for roughly a second. Emitted once per stale episode; a fresh reading
	/// re-arms it.
	@Serializable
	@SerialName("ScaleStale")
	object ScaleStale: Event()
	/// An incoming notification could not be decoded.
	@Serializable
	@SerialName("DecodeError")
	data class DecodeError(val content: EventDecodeErrorInner): Event()
}

/// Generated type representing the anonymous struct variant `WriteCharacteristic` of the `Command` Rust enum
@Serializable
data class CommandWriteCharacteristicInner (
	/// Which characteristic to write.
	val target: WriteTarget,
	/// The bytes to write.
	val data: List<UByte>
)

/// Generated type representing the anonymous struct variant `WriteScale` of the `Command` Rust enum
@Serializable
data class CommandWriteScaleInner (
	/// The bytes to write.
	val data: List<UByte>
)

/// A BLE write the shell should perform on the core's behalf.
/// 
/// The core owns the protocol, so a command carries the exact bytes; the shell
/// only needs a characteristic-UUID map, no protocol logic.
@Serializable
sealed class Command {
	/// Write `data` to a DE1 GATT characteristic.
	@Serializable
	@SerialName("WriteCharacteristic")
	data class WriteCharacteristic(val content: CommandWriteCharacteristicInner): Command()
	/// Write `data` to the connected scale's command characteristic.
	@Serializable
	@SerialName("WriteScale")
	data class WriteScale(val content: CommandWriteScaleInner): Command()
}

/// The result of feeding the core one input: what it observed (`events`) and
/// what it wants the shell to do (`commands`).
/// 
/// `#[non_exhaustive]` so further fields can be added without breaking the
/// bridge crates.
@Serializable
data class CoreOutput (
	/// The events observed, in order.
	val events: List<Event>,
	/// BLE writes the shell should perform, in order.
	val commands: List<Command>
)

/// DE1 top-level machine state. Discriminants match the firmware `MachineState`
/// enum (see protocol §4.1).
@Serializable
enum class MachineState(val string: String) {
	@SerialName("Sleep")
	Sleep("Sleep"),
	@SerialName("GoingToSleep")
	GoingToSleep("GoingToSleep"),
	@SerialName("Idle")
	Idle("Idle"),
	@SerialName("Busy")
	Busy("Busy"),
	@SerialName("Espresso")
	Espresso("Espresso"),
	@SerialName("Steam")
	Steam("Steam"),
	@SerialName("HotWater")
	HotWater("HotWater"),
	@SerialName("ShortCal")
	ShortCal("ShortCal"),
	@SerialName("SelfTest")
	SelfTest("SelfTest"),
	@SerialName("LongCal")
	LongCal("LongCal"),
	@SerialName("Descale")
	Descale("Descale"),
	@SerialName("FatalError")
	FatalError("FatalError"),
	@SerialName("Init")
	Init("Init"),
	/// A "no-op" value, used in RequestedState to mean "no change".
	@SerialName("NoRequest")
	NoRequest("NoRequest"),
	/// A command value: advance to the next espresso frame.
	@SerialName("SkipToNext")
	SkipToNext("SkipToNext"),
	@SerialName("HotWaterRinse")
	HotWaterRinse("HotWaterRinse"),
	@SerialName("SteamRinse")
	SteamRinse("SteamRinse"),
	@SerialName("Refill")
	Refill("Refill"),
	@SerialName("Clean")
	Clean("Clean"),
	@SerialName("InBootLoader")
	InBootLoader("InBootLoader"),
	@SerialName("AirPurge")
	AirPurge("AirPurge"),
	/// Scheduled-wake idle; firmware v1293 and later only.
	@SerialName("SchedIdle")
	SchedIdle("SchedIdle"),
}

/// Where an espresso shot is in its lifecycle.
@Serializable
enum class ShotPhase(val string: String) {
	/// No espresso shot in progress.
	@SerialName("Idle")
	Idle("Idle"),
	/// Heating and stabilising, before flow begins.
	@SerialName("Heating")
	Heating("Heating"),
	/// Preinfusion — wetting the puck at low pressure or flow.
	@SerialName("Preinfusion")
	Preinfusion("Preinfusion"),
	/// The main pour.
	@SerialName("Pouring")
	Pouring("Pouring"),
	/// Ending — flow has stopped and the group is draining.
	@SerialName("Ending")
	Ending("Ending"),
}

/// Why [`AutoStop`] decided to end the shot.
@Serializable
enum class StopReason(val string: String) {
	/// The weight target (SAW) was reached.
	@SerialName("Weight")
	Weight("Weight"),
	/// The volume target (SAV) was reached.
	@SerialName("Volume")
	Volume("Volume"),
	/// The maximum shot time was reached (legacy `espresso_max_time`).
	@SerialName("MaxTime")
	MaxTime("MaxTime"),
}

/// DE1 substate. Discriminants match the firmware enum (see protocol §4.2):
/// `0..=20` are operational substates, `200..=217` are error codes.
@Serializable
enum class SubState(val string: String) {
	@SerialName("Ready")
	Ready("Ready"),
	@SerialName("Heating")
	Heating("Heating"),
	@SerialName("FinalHeating")
	FinalHeating("FinalHeating"),
	@SerialName("Stabilising")
	Stabilising("Stabilising"),
	@SerialName("Preinfusion")
	Preinfusion("Preinfusion"),
	@SerialName("Pouring")
	Pouring("Pouring"),
	@SerialName("Ending")
	Ending("Ending"),
	@SerialName("Steaming")
	Steaming("Steaming"),
	@SerialName("DescaleInit")
	DescaleInit("DescaleInit"),
	@SerialName("DescaleFillGroup")
	DescaleFillGroup("DescaleFillGroup"),
	@SerialName("DescaleReturn")
	DescaleReturn("DescaleReturn"),
	@SerialName("DescaleGroup")
	DescaleGroup("DescaleGroup"),
	@SerialName("DescaleSteam")
	DescaleSteam("DescaleSteam"),
	@SerialName("CleanInit")
	CleanInit("CleanInit"),
	@SerialName("CleanFillGroup")
	CleanFillGroup("CleanFillGroup"),
	@SerialName("CleanSoak")
	CleanSoak("CleanSoak"),
	@SerialName("CleanGroup")
	CleanGroup("CleanGroup"),
	@SerialName("Refill")
	Refill("Refill"),
	@SerialName("PausedSteam")
	PausedSteam("PausedSteam"),
	@SerialName("UserNotPresent")
	UserNotPresent("UserNotPresent"),
	@SerialName("Puffing")
	Puffing("Puffing"),
	/// Died with a NaN.
	@SerialName("ErrorNaN")
	ErrorNaN("ErrorNaN"),
	/// Died with an infinity.
	@SerialName("ErrorInf")
	ErrorInf("ErrorInf"),
	/// Generic firmware error.
	@SerialName("ErrorGeneric")
	ErrorGeneric("ErrorGeneric"),
	/// Accelerometer not responding or unlocked.
	@SerialName("ErrorAcc")
	ErrorAcc("ErrorAcc"),
	/// Temperature sensor error.
	@SerialName("ErrorTSensor")
	ErrorTSensor("ErrorTSensor"),
	/// Pressure sensor error.
	@SerialName("ErrorPSensor")
	ErrorPSensor("ErrorPSensor"),
	/// Water-level sensor error.
	@SerialName("ErrorWLevel")
	ErrorWLevel("ErrorWLevel"),
	/// DIP switches forced an error state.
	@SerialName("ErrorDip")
	ErrorDip("ErrorDip"),
	/// An assertion failed.
	@SerialName("ErrorAssertion")
	ErrorAssertion("ErrorAssertion"),
	/// An unsafe value was assigned.
	@SerialName("ErrorUnsafe")
	ErrorUnsafe("ErrorUnsafe"),
	/// An invalid parameter was supplied.
	@SerialName("ErrorInvalidParm")
	ErrorInvalidParm("ErrorInvalidParm"),
	/// External flash access error.
	@SerialName("ErrorFlash")
	ErrorFlash("ErrorFlash"),
	/// Out of memory.
	@SerialName("ErrorOom")
	ErrorOom("ErrorOom"),
	/// A realtime deadline was missed.
	@SerialName("ErrorDeadline")
	ErrorDeadline("ErrorDeadline"),
	/// Current out of bounds (too high).
	@SerialName("ErrorHiCurrent")
	ErrorHiCurrent("ErrorHiCurrent"),
	/// Not enough current.
	@SerialName("ErrorLoCurrent")
	ErrorLoCurrent("ErrorLoCurrent"),
	/// Boot pressure test failed (no water?).
	@SerialName("ErrorBootFill")
	ErrorBootFill("ErrorBootFill"),
	/// Front power switch is off.
	@SerialName("ErrorNoAc")
	ErrorNoAc("ErrorNoAc"),
}

/// A writable DE1 GATT characteristic. The shell maps this to a UUID.
/// 
/// `#[non_exhaustive]`: profile-upload and MMR targets arrive later.
@Serializable
enum class WriteTarget(val string: String) {
	/// The DE1 `RequestedState` characteristic (`cuuid_02`).
	@SerialName("De1RequestedState")
	De1RequestedState("De1RequestedState"),
}

