/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get current account */
        get: operations["getCurrentAccount"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List shots
         * @description Returns shots sorted by start time (default) or `updated_at`.
         *
         *     Behavior differs by auth state:
         *     - Unauthenticated: only public shots
         *     - Authenticated: own shots
         */
        get: operations["listShots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shots/upload": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Upload shot export
         * @description Upload a shot file via one of:
         *     - `multipart/form-data` with `file`
         *     - `application/json` raw payload
         */
        post: operations["uploadShot"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shots/shared": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Resolve shared shot(s)
         * @description - With `code`: resolve a specific shared shot.
         *     - Without `code` and authenticated: return authenticated user's shared shots.
         *     - Without `code` and unauthenticated: returns 404.
         */
        get: operations["getSharedShots"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shots/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ShotId"];
            };
            cookie?: never;
        };
        /**
         * Get shot
         * @description Returns a shot by id.
         *
         *     When the authenticated user owns the shot, the response also includes `private_notes`.
         */
        get: operations["getShot"];
        put?: never;
        post?: never;
        /** Delete shot */
        delete: operations["deleteShot"];
        options?: never;
        head?: never;
        /** Update shot */
        patch: operations["updateShot"];
        trace?: never;
    };
    "/shots/{id}/download": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download shot (alias of get shot) */
        get: operations["downloadShot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/shots/{id}/profile": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download shot profile file */
        get: operations["downloadShotProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roasters": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List roasters */
        get: operations["listRoasters"];
        put?: never;
        /** Create roaster */
        post: operations["createRoaster"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roasters/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roaster_id: components["parameters"]["RoasterId"];
            };
            cookie?: never;
        };
        /** Get roaster */
        get: operations["getRoaster"];
        put?: never;
        post?: never;
        /** Delete roaster */
        delete: operations["deleteRoaster"];
        options?: never;
        head?: never;
        /** Update roaster */
        patch: operations["updateRoaster"];
        trace?: never;
    };
    "/coffee_bags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List coffee bags */
        get: operations["listCoffeeBags"];
        put?: never;
        /** Create coffee bag */
        post: operations["createCoffeeBag"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/coffee_bags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CoffeeBagId"];
            };
            cookie?: never;
        };
        /** Get coffee bag */
        get: operations["getCoffeeBag"];
        put?: never;
        post?: never;
        /** Delete coffee bag */
        delete: operations["deleteCoffeeBag"];
        options?: never;
        head?: never;
        /** Update coffee bag */
        patch: operations["updateCoffeeBag"];
        trace?: never;
    };
    "/roasters/{roaster_id}/coffee_bags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy nested coffee bag index
         * @deprecated
         * @description Deprecated alias that redirects to `/coffee_bags?roaster_id={roaster_id}`.
         */
        get: operations["legacyNestedCoffeeBagsIndex"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/roasters/{roaster_id}/coffee_bags/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Legacy nested coffee bag show
         * @deprecated
         * @description Deprecated alias that redirects to `/coffee_bags/{id}`.
         */
        get: operations["legacyNestedCoffeeBagShow"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * @example {
         *       "error": "Shot not found"
         *     }
         */
        Error: {
            error: string;
        };
        /**
         * @example {
         *       "success": true
         *     }
         */
        DeleteResult: {
            success: boolean;
        };
        Paging: {
            count: number;
            page: number;
            limit: number;
            pages: number;
        };
        MeResponse: {
            /** Format: uuid */
            id: string;
            name: string;
            public: boolean;
            /** Format: uri */
            avatar_url: string;
        };
        ShotSummary: {
            /** Format: uuid */
            id: string;
            /**
             * Format: int64
             * @description Shot start timestamp (unix seconds).
             */
            clock: number;
            /**
             * Format: int64
             * @description Last update timestamp (unix seconds).
             */
            updated_at: number;
        };
        ShotListResponse: {
            data: components["schemas"]["ShotSummary"][];
            paging: components["schemas"]["Paging"];
        };
        /** @description Flexible shot payload. Keys vary by `format` and integration source. */
        ShotDetail: components["schemas"]["DefaultShotDetail"] | components["schemas"]["BeanconquerorShotDetail"];
        /**
         * @description Default shot response shape used by Visualizer's native serializer.
         *
         *     `private_notes` is only included when the authenticated user owns the shot.
         *     Some optional Visualizer-specific fields may be omitted entirely when blank.
         * @example {
         *       "id": "15d4ec9f-7f86-4f63-b2ac-cfce8277f33f",
         *       "user_id": "0c2f8248-7d67-44c1-a89a-3a6c0d468875",
         *       "profile_title": "Rao Allonge",
         *       "drink_weight": "42.1",
         *       "bean_weight": "20.0",
         *       "start_time": "2026-03-09T08:12:00Z",
         *       "updated_at": 1741517580,
         *       "timeframe": [
         *         0,
         *         1.2,
         *         2.4
         *       ],
         *       "data": {
         *         "espresso_pressure": [
         *           0.5,
         *           2.7,
         *           8.4
         *         ],
         *         "espresso_flow": [
         *           0,
         *           1.1,
         *           2.3
         *         ]
         *       },
         *       "tags": [
         *         "daily",
         *         "washed"
         *       ]
         *     }
         */
        DefaultShotDetail: {
            /** Format: uuid */
            id?: string;
            /** Format: uuid */
            user_id?: string | null;
            duration?: number | null;
            profile_title?: string | null;
            drink_tds?: string | null;
            drink_ey?: string | null;
            espresso_enjoyment?: number | null;
            bean_weight?: string | null;
            drink_weight?: string | null;
            grinder_model?: string | null;
            grinder_setting?: string | null;
            bean_brand?: string | null;
            bean_type?: string | null;
            roast_date?: string | null;
            espresso_notes?: string | null;
            roast_level?: string | null;
            bean_notes?: string | null;
            private_notes?: string | null;
            barista?: string | null;
            fragrance?: number | null;
            aroma?: number | null;
            flavor?: number | null;
            aftertaste?: number | null;
            acidity?: number | null;
            bitterness?: number | null;
            sweetness?: number | null;
            mouthfeel?: number | null;
            /** Format: date-time */
            start_time?: string;
            /** Format: int64 */
            updated_at?: number;
            user_name?: string;
            metadata?: components["schemas"]["ShotMetadata"] | null;
            tags?: string[];
            /** Format: uri */
            profile_url?: string;
            /** Format: uri */
            image_url?: string;
            /** Format: uuid */
            roaster_id?: string;
            /** Format: uuid */
            coffee_bag_id?: string;
            timeframe?: number[];
            data?: components["schemas"]["ShotSeriesData"];
            brewdata?: components["schemas"]["ShotBrewdata"];
        };
        /**
         * @description Shot response shape used when `format=beanconqueror`.
         *
         *     `meta.visualizer.private_notes` is only included when the authenticated user owns the shot.
         *     Some optional `meta.visualizer` fields may be omitted entirely when blank.
         * @example {
         *       "bean": {
         *         "roaster": "Sey",
         *         "name": "Kenya Kii",
         *         "roast": "Light"
         *       },
         *       "mill": {
         *         "name": "EK43"
         *       },
         *       "brew": {
         *         "grind_size": "7.5",
         *         "brew_beverage_quantity": "40",
         *         "grind_weight": "20"
         *       },
         *       "preparation": {
         *         "name": "Beanconqueror"
         *       },
         *       "meta": {
         *         "visualizer": {
         *           "shot_id": "15d4ec9f-7f86-4f63-b2ac-cfce8277f33f",
         *           "private_notes": "Dialed in and syrupy"
         *         }
         *       }
         *     }
         */
        BeanconquerorShotDetail: {
            bean?: components["schemas"]["BeanconquerorBean"];
            mill?: components["schemas"]["BeanconquerorMill"];
            brew?: components["schemas"]["BeanconquerorBrew"];
            preparation?: components["schemas"]["BeanconquerorPreparation"];
            meta?: components["schemas"]["BeanconquerorMeta"];
            brewdata?: components["schemas"]["ShotBrewdata"];
            timeframe?: number[];
            data?: components["schemas"]["ShotSeriesData"];
        };
        SharedShotsResponse: components["schemas"]["ShotDetail"] | components["schemas"]["ShotDetail"][];
        /** @description Raw JSON shot export payload from supported tools/devices. */
        ShotUploadPayload: components["schemas"]["BeanconquerorUploadPayload"] | components["schemas"]["DecentUploadPayload"] | components["schemas"]["GaggiuinoUploadPayload"] | components["schemas"]["GaggiMateUploadPayload"] | components["schemas"]["MeticulousUploadPayload"];
        BeanconquerorUploadPayload: {
            bean?: components["schemas"]["BeanconquerorBean"];
            mill?: components["schemas"]["BeanconquerorMill"];
            brew: components["schemas"]["BeanconquerorBrew"];
            preparation?: components["schemas"]["BeanconquerorPreparation"];
            /** @description Beanconqueror brew flow series keyed by metric. */
            brewFlow?: Record<string, never>;
        };
        DecentUploadPayload: {
            /** Format: int64 */
            timestamp: number;
            elapsed?: number[];
            /** @description Exported profile settings. */
            profile?: Record<string, never>;
            pressure?: components["schemas"]["DecentSeriesPayload"];
            flow?: components["schemas"]["DecentSeriesPayload"];
            temperature?: components["schemas"]["DecentTemperaturePayload"];
            totals?: components["schemas"]["DecentTotalsPayload"];
        };
        GaggiuinoUploadPayload: {
            timestamp?: number;
            /** @description Gaggiuino profile payload. */
            profile?: Record<string, never>;
            datapoints: components["schemas"]["GaggiuinoDatapoint"][];
        };
        GaggiMateUploadPayload: {
            /** Format: int64 */
            timestamp: number;
            profile?: string | components["schemas"]["GaggiMateProfile"];
            samples: components["schemas"]["GaggiMateSample"][];
        };
        MeticulousUploadPayload: {
            /** Format: int64 */
            time: number;
            profile_name: string;
            /** @description Meticulous profile payload. */
            profile?: Record<string, never>;
            data: components["schemas"]["MeticulousDatapoint"][];
        };
        ShotUploadResult: {
            /** Format: uuid */
            id: string;
        };
        /** @description Raw brew payload preserved from the original integration source. */
        ShotBrewdata: components["schemas"]["BeanconquerorUploadPayload"] | components["schemas"]["DecentUploadPayload"] | components["schemas"]["GaggiuinoUploadPayload"] | components["schemas"]["GaggiMateUploadPayload"] | components["schemas"]["MeticulousUploadPayload"];
        /**
         * @description Optional user-defined metadata attached to the shot.
         * @example {
         *       "grinder_burrs": "SSP HU",
         *       "water_recipe": "Rao/Perger"
         *     }
         */
        ShotMetadata: Record<string, never>;
        /** @description Common shot time-series arrays keyed by metric name. */
        ShotSeriesData: {
            espresso_pressure?: components["schemas"]["ShotSeries"];
            espresso_flow?: components["schemas"]["ShotSeries"];
            espresso_weight?: components["schemas"]["ShotSeries"];
            espresso_flow_weight?: components["schemas"]["ShotSeries"];
            espresso_pressure_goal?: components["schemas"]["ShotSeries"];
            espresso_flow_goal?: components["schemas"]["ShotSeries"];
            espresso_temperature_goal?: components["schemas"]["ShotSeries"];
            espresso_temperature_mix?: components["schemas"]["ShotSeries"];
            espresso_temperature_basket?: components["schemas"]["ShotSeries"];
            espresso_water_dispensed?: components["schemas"]["ShotSeries"];
            espresso_state_change?: components["schemas"]["ShotSeries"];
        };
        ShotSeries: (number | string | boolean | null)[];
        BeanconquerorBean: {
            roaster?: string;
            name?: string;
            roast?: string;
            /** Format: date-time */
            roastingDate?: string;
        };
        BeanconquerorMill: {
            name?: string;
        };
        BeanconquerorBrew: {
            grind_size?: string;
            brew_beverage_quantity?: string;
            grind_weight?: string;
            tds?: string;
            ey?: string;
        };
        BeanconquerorPreparation: {
            name?: string;
        };
        BeanconquerorMeta: {
            /**
             * @description Visualizer-specific metadata for the shot.
             *
             *     Owner-only fields such as `private_notes` are only included when the authenticated user owns the shot.
             *     Some optional fields may be omitted entirely when blank.
             */
            visualizer?: {
                /** Format: uuid */
                shot_id?: string;
                /** Format: uuid */
                user_id?: string | null;
                /** Format: int64 */
                updated_at?: number;
                duration?: number | null;
                espresso_enjoyment?: number | null;
                fragrance?: number | null;
                aroma?: number | null;
                flavor?: number | null;
                aftertaste?: number | null;
                acidity?: number | null;
                bitterness?: number | null;
                sweetness?: number | null;
                mouthfeel?: number | null;
                espresso_notes?: string | null;
                bean_notes?: string | null;
                barista?: string | null;
                metadata?: components["schemas"]["ShotMetadata"] | null;
                tags?: string[];
                /** Format: uuid */
                roaster_id?: string;
                /** Format: uuid */
                coffee_bag_id?: string;
                /** Format: date-time */
                start_time?: string;
                user_name?: string;
                private_notes?: string | null;
                /** Format: uri */
                profile_url?: string;
                /** Format: uri */
                image_url?: string;
            };
        };
        DecentSeriesPayload: {
            pressure?: components["schemas"]["ShotSeries"];
            flow?: components["schemas"]["ShotSeries"];
            by_weight?: components["schemas"]["ShotSeries"];
            by_weight_raw?: components["schemas"]["ShotSeries"];
            goal?: components["schemas"]["ShotSeries"];
        };
        DecentTemperaturePayload: {
            basket?: components["schemas"]["ShotSeries"];
            mix?: components["schemas"]["ShotSeries"];
            goal?: components["schemas"]["ShotSeries"];
        };
        DecentTotalsPayload: {
            weight?: components["schemas"]["ShotSeries"];
            water_dispensed?: components["schemas"]["ShotSeries"];
        };
        GaggiuinoDatapoint: {
            timeInShot?: number;
            pressure?: number;
            pumpFlow?: number;
            shotWeight?: number;
            targetPressure?: number;
            targetPumpFlow?: number;
            targetTemperature?: number;
            temperature?: number;
            waterPumped?: number;
            weightFlow?: number;
        };
        GaggiMateProfile: {
            label?: string;
        };
        GaggiMateSample: {
            t?: number;
            cp?: number;
            fl?: number;
            tp?: number;
            tf?: number;
            tt?: number;
            ct?: number;
            v?: number;
            ev?: number;
            vf?: number;
            pf?: number;
        };
        MeticulousDatapoint: {
            time?: number;
            status?: string;
            shot?: {
                pressure?: number;
                flow?: number;
                weight?: number;
                gravimetric_flow?: number;
                setpoints?: {
                    pressure?: number;
                    flow?: number;
                };
            };
            sensors?: {
                tube?: number;
            };
        };
        ShotUpdateRequest: {
            shot: {
                profile_title?: string | null;
                barista?: string | null;
                bean_weight?: string | null;
                private_notes?: string | null;
                fragrance?: number | null;
                aroma?: number | null;
                flavor?: number | null;
                aftertaste?: number | null;
                acidity?: number | null;
                bitterness?: number | null;
                sweetness?: number | null;
                mouthfeel?: number | null;
                /** Format: uuid */
                canonical_coffee_bag_id?: string | null;
                /** Format: uuid */
                coffee_bag_id?: string | null;
                tag_list?: string[];
                metadata?: {
                    [key: string]: unknown;
                } | null;
            } & {
                [key: string]: unknown;
            };
        };
        RoasterSummary: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        RoasterListResponse: {
            data: components["schemas"]["RoasterSummary"][];
            paging: components["schemas"]["Paging"];
        };
        RoasterDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: uri */
            website?: string | null;
            /** Format: uri */
            image_url?: string | null;
        };
        RoasterWriteRequest: {
            roaster: {
                name?: string;
                /** Format: uri */
                website?: string | null;
                /** Format: uuid */
                canonical_roaster_id?: string | null;
            };
        };
        CoffeeBagSummary: {
            /** Format: uuid */
            id: string;
            name: string;
        };
        CoffeeBagListResponse: {
            data: components["schemas"]["CoffeeBagSummary"][];
            paging: components["schemas"]["Paging"];
        };
        CoffeeBagDetail: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: date */
            roast_date?: string | null;
            /** Format: date */
            frozen_date?: string | null;
            /** Format: date */
            defrosted_date?: string | null;
            roast_level?: string | null;
            country?: string | null;
            region?: string | null;
            farm?: string | null;
            farmer?: string | null;
            variety?: string | null;
            elevation?: string | null;
            processing?: string | null;
            harvest_time?: string | null;
            quality_score?: string | null;
            tasting_notes?: string | null;
            place_of_purchase?: string | null;
            /** Format: uri */
            url?: string | null;
            notes?: string | null;
            /** Format: date-time */
            archived_at?: string | null;
            /** Format: uri */
            image_url?: string | null;
            metadata?: {
                [key: string]: unknown;
            } | null;
        };
        CoffeeBagWriteRequest: {
            coffee_bag: {
                name?: string;
                /** Format: uuid */
                roaster_id?: string | null;
                /** Format: uuid */
                canonical_coffee_bag_id?: string | null;
                /** Format: date */
                roast_date?: string | null;
                /** Format: date */
                frozen_date?: string | null;
                /** Format: date */
                defrosted_date?: string | null;
                roast_level?: string | null;
                country?: string | null;
                region?: string | null;
                farm?: string | null;
                farmer?: string | null;
                variety?: string | null;
                elevation?: string | null;
                processing?: string | null;
                harvest_time?: string | null;
                quality_score?: string | null;
                tasting_notes?: string | null;
                place_of_purchase?: string | null;
                /** Format: uri */
                url?: string | null;
                notes?: string | null;
                metadata?: {
                    [key: string]: unknown;
                } | null;
            };
        };
    };
    responses: {
        /** @description Too many requests. The API rate limit has been exceeded. */
        RateLimited: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                /**
                 * @example {
                 *       "error": "Too many requests. Please try again later."
                 *     }
                 */
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description 1-based page number (default 1). */
        Page: number;
        /** @description Items per page (default 10, max 100). */
        Items: number;
        /** @description Set to `updated_at` for updated-time sorting. Omit for start-time sorting. */
        ShotSort: "updated_at";
        ShotId: string;
        RoasterId: string;
        CoffeeBagId: string;
        /** @description Shared shot code (case-insensitive). */
        SharedCode: string;
        /** @description Optional output format used by shot serializers. Defaults to `default` when omitted. Legacy `decent` remains accepted as an alias for backward compatibility. */
        ShotFormat: "default" | "beanconqueror";
        /** @description Profile output format. `tcl` is used when available and format is not `json`. */
        ProfileFormat: "csv" | "json" | "tcl";
        /** @description When present, omits full shot information payload. */
        Essentials: string | boolean;
        /** @description When present on shared shot responses, includes detailed shot information. */
        WithData: string | boolean;
        /** @description Filter coffee bags by roaster ID. */
        RoasterFilter: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getCurrentAccount: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Authenticated account details. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listShots: {
        parameters: {
            query?: {
                /** @description 1-based page number (default 1). */
                page?: components["parameters"]["Page"];
                /** @description Items per page (default 10, max 100). */
                items?: components["parameters"]["Items"];
                /** @description Set to `updated_at` for updated-time sorting. Omit for start-time sorting. */
                sort?: components["parameters"]["ShotSort"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated shot summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotListResponse"];
                };
            };
            /** @description Invalid pagination/sort. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    uploadShot: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    file: string;
                };
                "application/json": components["schemas"]["ShotUploadPayload"];
            };
        };
        responses: {
            /** @description Shot created. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotUploadResult"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Missing OAuth scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Could not parse or persist shot. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getSharedShots: {
        parameters: {
            query?: {
                /** @description Shared shot code (case-insensitive). */
                code?: components["parameters"]["SharedCode"];
                /** @description Optional output format used by shot serializers. Defaults to `default` when omitted. Legacy `decent` remains accepted as an alias for backward compatibility. */
                format?: components["parameters"]["ShotFormat"];
                /** @description When present on shared shot responses, includes detailed shot information. */
                with_data?: components["parameters"]["WithData"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shared shot or list of shared shots. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SharedShotsResponse"];
                };
            };
            /** @description Shared shot not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getShot: {
        parameters: {
            query?: {
                /** @description Optional output format used by shot serializers. Defaults to `default` when omitted. Legacy `decent` remains accepted as an alias for backward compatibility. */
                format?: components["parameters"]["ShotFormat"];
                /** @description When present, omits full shot information payload. */
                essentials?: components["parameters"]["Essentials"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ShotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shot detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotDetail"];
                };
            };
            /** @description Shot not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    deleteShot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ShotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shot deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Shot not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    updateShot: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["ShotId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ShotUpdateRequest"];
            };
        };
        responses: {
            /** @description Updated shot detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotDetail"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Not authorized. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Shot not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Invalid request payload. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    downloadShot: {
        parameters: {
            query?: {
                /** @description Optional output format used by shot serializers. Defaults to `default` when omitted. Legacy `decent` remains accepted as an alias for backward compatibility. */
                format?: components["parameters"]["ShotFormat"];
                /** @description When present, omits full shot information payload. */
                essentials?: components["parameters"]["Essentials"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ShotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Shot detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ShotDetail"];
                };
            };
            /** @description Shot not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    downloadShotProfile: {
        parameters: {
            query?: {
                /** @description Profile output format. `tcl` is used when available and format is not `json`. */
                format?: components["parameters"]["ProfileFormat"];
            };
            header?: never;
            path: {
                id: components["parameters"]["ShotId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Profile file stream. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "text/csv": string;
                    "application/x-tcl": string;
                    "application/json": string;
                };
            };
            /** @description Shot not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Shot has no profile. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listRoasters: {
        parameters: {
            query?: {
                /** @description 1-based page number (default 1). */
                page?: components["parameters"]["Page"];
                /** @description Items per page (default 10, max 100). */
                items?: components["parameters"]["Items"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated roaster summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoasterListResponse"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    createRoaster: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoasterWriteRequest"];
            };
        };
        responses: {
            /** @description Roaster created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoasterDetail"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Premium access or missing OAuth scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getRoaster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roaster_id: components["parameters"]["RoasterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roaster detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoasterDetail"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Roaster not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    deleteRoaster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roaster_id: components["parameters"]["RoasterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Roaster deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Premium access or missing OAuth scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Roaster not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    updateRoaster: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roaster_id: components["parameters"]["RoasterId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["RoasterWriteRequest"];
            };
        };
        responses: {
            /** @description Roaster updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoasterDetail"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Premium access or missing OAuth scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Roaster not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    listCoffeeBags: {
        parameters: {
            query?: {
                /** @description 1-based page number (default 1). */
                page?: components["parameters"]["Page"];
                /** @description Items per page (default 10, max 100). */
                items?: components["parameters"]["Items"];
                /** @description Filter coffee bags by roaster ID. */
                roaster_id?: components["parameters"]["RoasterFilter"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Paginated coffee bag summaries. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeBagListResponse"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    createCoffeeBag: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoffeeBagWriteRequest"];
            };
        };
        responses: {
            /** @description Coffee bag created. */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeBagDetail"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Premium access or missing OAuth scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    getCoffeeBag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CoffeeBagId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coffee bag detail. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeBagDetail"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Coffee bag not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    deleteCoffeeBag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CoffeeBagId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Coffee bag deleted. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeleteResult"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Premium access or missing OAuth scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Coffee bag not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    updateCoffeeBag: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["CoffeeBagId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CoffeeBagWriteRequest"];
            };
        };
        responses: {
            /** @description Coffee bag updated. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CoffeeBagDetail"];
                };
            };
            /** @description Authentication required. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Premium access or missing OAuth scope. */
            403: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Coffee bag not found. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            /** @description Validation failed. */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Error"];
                };
            };
            429: components["responses"]["RateLimited"];
        };
    };
    legacyNestedCoffeeBagsIndex: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roaster_id: components["parameters"]["RoasterId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Permanent redirect to root coffee bag index. */
            301: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
    legacyNestedCoffeeBagShow: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                roaster_id: components["parameters"]["RoasterId"];
                id: components["parameters"]["CoffeeBagId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Permanent redirect to root coffee bag show. */
            301: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            429: components["responses"]["RateLimited"];
        };
    };
}
