package coffee.crema.drive

import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import kotlinx.serialization.Serializable
import kotlinx.serialization.json.Json
import kotlinx.serialization.json.JsonObject
import kotlinx.serialization.json.contentOrNull
import kotlinx.serialization.json.jsonObject
import kotlinx.serialization.json.jsonPrimitive
import java.io.IOException
import java.net.HttpURLConnection
import java.net.URL
import java.net.URLEncoder

/*
 * Google Drive OAuth — Authorization-Code + PKCE against Google, the Android
 * twin of `web/src/lib/drive/oauth.ts`. Public client (no secret); scope
 * `drive.file` (the app only ever sees backups it created). A Custom Tab handles
 * the consent hop; Google bounces back to the reversed-client-id custom scheme
 * ([googleRedirectUri]), which the manifest routes to MainActivity.
 *
 * The PKCE verifier/state are generated by the sign-in flow (reusing the
 * Visualizer helpers) and persisted in [DriveStore]; this file owns the URL
 * builder + token endpoint. `access_type=offline` + `prompt=consent` guarantee
 * a refresh token (Google omits it on silent re-auth, which would strand us
 * once the first one is gone).
 */

const val GOOGLE_AUTHORIZE_URL = "https://accounts.google.com/o/oauth2/v2/auth"
const val GOOGLE_TOKEN_URL = "https://oauth2.googleapis.com/token"
const val DRIVE_SCOPE = "https://www.googleapis.com/auth/drive.file"

/** A successful exchange — persisted by [DriveStore]. */
@Serializable
data class DriveTokenSet(
    val accessToken: String,
    /** Present only on the first consent (`access_type=offline` + `prompt=consent`);
     *  carried forward on silent refresh. */
    val refreshToken: String? = null,
    /** Absolute expiry, ms since epoch. */
    val expiresAt: Long,
    val scope: String = DRIVE_SCOPE,
    val tokenType: String = "Bearer",
)

/**
 * The scheme half of the reversed-client-id redirect — also the value of the
 * `googleRedirectScheme` manifest placeholder. For an Android OAuth client,
 * Google requires `com.googleusercontent.apps.<id>` (NOT an arbitrary
 * `crema://` scheme like the Visualizer flow uses).
 */
fun reversedClientScheme(clientId: String): String =
    if (clientId.endsWith(".apps.googleusercontent.com")) {
        "com.googleusercontent.apps." + clientId.removeSuffix(".apps.googleusercontent.com")
    } else {
        clientId
    }

/** Full reversed-client-id redirect URI Google bounces back to. */
fun googleRedirectUri(clientId: String): String = "${reversedClientScheme(clientId)}:/oauth2redirect"

/** Build the consent URL for the Custom-Tab hop. */
fun buildGoogleAuthorizeUrl(clientId: String, state: String, codeChallenge: String): String {
    fun enc(v: String) = URLEncoder.encode(v, "UTF-8")
    return GOOGLE_AUTHORIZE_URL +
        "?response_type=code" +
        "&client_id=${enc(clientId)}" +
        "&redirect_uri=${enc(googleRedirectUri(clientId))}" +
        "&scope=${enc(DRIVE_SCOPE)}" +
        "&state=${enc(state)}" +
        "&code_challenge=${enc(codeChallenge)}" +
        "&code_challenge_method=S256" +
        "&access_type=offline" +
        "&prompt=consent" +
        "&include_granted_scopes=true"
}

private fun formBody(params: Map<String, String>): String =
    params.entries.joinToString("&") { (k, v) ->
        "${URLEncoder.encode(k, "UTF-8")}=${URLEncoder.encode(v, "UTF-8")}"
    }

/** POST the token endpoint and map the wire response → [DriveTokenSet]. Google
 *  keeps the same refresh token across refreshes, so carry [fallbackRefresh]. */
private suspend fun postToken(
    params: Map<String, String>,
    fallbackRefresh: String?,
    json: Json,
): DriveTokenSet =
    withContext(Dispatchers.IO) {
        val conn = (URL(GOOGLE_TOKEN_URL).openConnection() as HttpURLConnection).apply {
            requestMethod = "POST"
            connectTimeout = 15_000
            readTimeout = 20_000
            doOutput = true
            setRequestProperty("Content-Type", "application/x-www-form-urlencoded")
            setRequestProperty("Accept", "application/json")
        }
        try {
            conn.outputStream.use { it.write(formBody(params).toByteArray(Charsets.UTF_8)) }
            val status = conn.responseCode
            val body = (if (status in 200..299) conn.inputStream else conn.errorStream)
                ?.use { String(it.readBytes(), Charsets.UTF_8) }.orEmpty()
            val obj: JsonObject = runCatching { json.parseToJsonElement(body).jsonObject }
                .getOrElse { throw IOException("Google token endpoint returned non-JSON (HTTP $status).") }
            fun str(k: String) = obj[k]?.jsonPrimitive?.contentOrNull
            val access = str("access_token")
            if (status !in 200..299 || access == null) {
                throw IOException("Google token endpoint: ${str("error_description") ?: str("error") ?: "HTTP $status"}")
            }
            val ttlS = obj["expires_in"]?.jsonPrimitive?.contentOrNull?.toLongOrNull() ?: 3600L
            DriveTokenSet(
                accessToken = access,
                refreshToken = str("refresh_token") ?: fallbackRefresh,
                expiresAt = System.currentTimeMillis() + ttlS * 1000,
                scope = str("scope") ?: DRIVE_SCOPE,
                tokenType = str("token_type") ?: "Bearer",
            )
        } finally {
            conn.disconnect()
        }
    }

/** Trade an authorization code for tokens (public client — verifier, no secret). */
suspend fun exchangeCodeForDriveToken(
    clientId: String,
    code: String,
    verifier: String,
    json: Json,
): DriveTokenSet =
    postToken(
        mapOf(
            "grant_type" to "authorization_code",
            "code" to code,
            "redirect_uri" to googleRedirectUri(clientId),
            "client_id" to clientId,
            "code_verifier" to verifier,
        ),
        fallbackRefresh = null,
        json = json,
    )

/** Swap a refresh token for a fresh access token (Google keeps the refresh token). */
suspend fun refreshDriveToken(clientId: String, refreshToken: String, json: Json): DriveTokenSet =
    postToken(
        mapOf(
            "grant_type" to "refresh_token",
            "refresh_token" to refreshToken,
            "client_id" to clientId,
        ),
        fallbackRefresh = refreshToken,
        json = json,
    )
